import type {
  BillingMenuItem,
  CustomerProfile,
  HeldBill,
  BillingCategory,
} from "@/types/posBilling";

export const BILLING_CATEGORIES: BillingCategory[] = [
  "All Items",
  "Starters",
  "Main Course",
  "Breads & Rice",
  "Continental & Pasta",
  "Desserts",
  "Beverages & Shakes",
  "Bar & Cocktails",
  "Combos",
];

export const MOCK_MENU_ITEMS: BillingMenuItem[] = [
  {
    id: "itm-101",
    code: "#101",
    name: "Paneer Tikka Angara",
    category: "Starters",
    diet: "veg",
    price: 340,
    inStock: true,
    stockCount: 28,
    prepTimeMinutes: 15,
    isPopular: true,
    description: "Charcoal smoked cottage cheese marinated in fiery spices & hung curd",
    variants: [
      { id: "v1-half", name: "Half (4 Pcs)", price: 220 },
      { id: "v1-full", name: "Full (8 Pcs)", price: 340 },
    ],
    modifierGroups: [
      {
        id: "mg-spice",
        name: "Spice Level",
        maxSelect: 1,
        options: [
          { id: "sp-mild", name: "Mild / Less Spicy", price: 0 },
          { id: "sp-med", name: "Regular Spice", price: 0 },
          { id: "sp-extra", name: "Extra Angara Spicy", price: 0 },
        ],
      },
      {
        id: "mg-addon",
        name: "Add-ons & Dips",
        maxSelect: 2,
        options: [
          { id: "ao-mint", name: "Extra Mint Chutney & Onions", price: 30 },
          { id: "ao-cheese", name: "Grated Cheddar Melt Topping", price: 60 },
        ],
      },
    ],
  },
  {
    id: "itm-102",
    code: "#102",
    name: "Murgh Malai Tikka",
    category: "Starters",
    diet: "non_veg",
    price: 420,
    inStock: true,
    stockCount: 19,
    prepTimeMinutes: 18,
    isPopular: true,
    description: "Tender chicken chunks marinated in cream, cardamom, cashew paste & grilled",
    variants: [
      { id: "v2-half", name: "Half (4 Pcs)", price: 260 },
      { id: "v2-full", name: "Full (8 Pcs)", price: 420 },
    ],
    modifierGroups: [
      {
        id: "mg-prep",
        name: "Chef Style",
        maxSelect: 1,
        options: [
          { id: "prep-classic", name: "Classic Clay Oven Tandoor", price: 0 },
          { id: "prep-butter", name: "Tossed in Amritsari Butter", price: 40 },
        ],
      },
    ],
  },
  {
    id: "itm-103",
    code: "#103",
    name: "Crispy Corn & Water Chestnut",
    category: "Starters",
    diet: "veg",
    price: 290,
    inStock: true,
    stockCount: 35,
    prepTimeMinutes: 12,
    description: "Golden fried sweet corn kernels tossed with crushed pepper, scallions and lime",
  },
  {
    id: "itm-104",
    code: "#104",
    name: "Galouti Kebab Sliders",
    category: "Starters",
    diet: "non_veg",
    price: 460,
    inStock: true,
    stockCount: 12,
    prepTimeMinutes: 20,
    isChefSpecial: true,
    description: "Melt in mouth minced mutton kebabs served over mini saffron sheermal buns",
  },
  {
    id: "itm-105",
    code: "#105",
    name: "Butter Chicken (Grandma Recipe)",
    category: "Main Course",
    diet: "non_veg",
    price: 520,
    inStock: true,
    stockCount: 40,
    prepTimeMinutes: 18,
    isPopular: true,
    isChefSpecial: true,
    description: "Smoked tandoori chicken cooked in velvety tomato, makhani gravy and cashew paste",
    variants: [
      { id: "v3-boneless", name: "Boneless Meat", price: 560 },
      { id: "v3-bonein", name: "Classic Bone-in", price: 520 },
    ],
    modifierGroups: [
      {
        id: "mg-butter",
        name: "Gravy Texture",
        maxSelect: 1,
        options: [
          { id: "gv-mild", name: "Sweetish Creamy Makhani", price: 0 },
          { id: "gv-spicy", name: "Spicy Delhi Street Style", price: 0 },
        ],
      },
    ],
  },
  {
    id: "itm-106",
    code: "#106",
    name: "Dal Makhani 24-Hour Slow Cooked",
    category: "Main Course",
    diet: "veg",
    price: 360,
    inStock: true,
    stockCount: 50,
    prepTimeMinutes: 10,
    isPopular: true,
    description: "Black lentils simmered overnight with cream, butter and sun-dried fenugreek",
  },
  {
    id: "itm-107",
    code: "#107",
    name: "Paneer Lababdar",
    category: "Main Course",
    diet: "veg",
    price: 410,
    inStock: true,
    stockCount: 22,
    prepTimeMinutes: 16,
    description: "Cottage cheese cubes bathed in rich onion tomato gravy with grated paneer",
  },
  {
    id: "itm-108",
    code: "#108",
    name: "Mutton Rogan Josh Kashmiri",
    category: "Main Course",
    diet: "non_veg",
    price: 640,
    inStock: true,
    stockCount: 15,
    prepTimeMinutes: 22,
    isChefSpecial: true,
    description:
      "Slow-braised spring lamb shanks flavored with aromatic Kashmiri chillies and ratan jot",
  },
  {
    id: "itm-109",
    code: "#109",
    name: "Garlic Butter Naan",
    category: "Breads & Rice",
    diet: "veg",
    price: 95,
    inStock: true,
    stockCount: 99,
    prepTimeMinutes: 6,
    description: "Refined flour flatbread brushed with garlic butter and fresh coriander",
  },
  {
    id: "itm-110",
    code: "#110",
    name: "Laccha Paratha",
    category: "Breads & Rice",
    diet: "veg",
    price: 85,
    inStock: true,
    stockCount: 99,
    prepTimeMinutes: 6,
  },
  {
    id: "itm-111",
    code: "#111",
    name: "Dum Awadhi Gosht Biryani",
    category: "Breads & Rice",
    diet: "non_veg",
    price: 580,
    inStock: true,
    stockCount: 18,
    prepTimeMinutes: 15,
    isPopular: true,
    description: "Long grain basmati sealed in dough pot with tender lamb cuts, saffron & spices",
  },
  {
    id: "itm-112",
    code: "#112",
    name: "Subz Dum Biryani Handi",
    category: "Breads & Rice",
    diet: "veg",
    price: 390,
    inStock: true,
    stockCount: 24,
    prepTimeMinutes: 15,
  },
  {
    id: "itm-113",
    code: "#113",
    name: "Truffle Mushroom Risotto",
    category: "Continental & Pasta",
    diet: "veg",
    price: 490,
    inStock: true,
    stockCount: 14,
    prepTimeMinutes: 18,
    description: "Arborio rice with wild forest mushrooms, parmesan crisp and white truffle oil",
  },
  {
    id: "itm-114",
    code: "#114",
    name: "Penne Alfredo with Smoked Chicken",
    category: "Continental & Pasta",
    diet: "non_veg",
    price: 470,
    inStock: true,
    stockCount: 16,
    prepTimeMinutes: 16,
  },
  {
    id: "itm-115",
    code: "#115",
    name: "Egg Roast with Malabar Parotta",
    category: "Main Course",
    diet: "egg",
    price: 320,
    inStock: true,
    stockCount: 20,
    prepTimeMinutes: 14,
  },
  {
    id: "itm-116",
    code: "#116",
    name: "Sizzling Brownie with Vanilla Gelato",
    category: "Desserts",
    diet: "egg",
    price: 260,
    inStock: true,
    stockCount: 30,
    prepTimeMinutes: 8,
    isPopular: true,
  },
  {
    id: "itm-117",
    code: "#117",
    name: "Gulab Jamun with Rabdi Parfait",
    category: "Desserts",
    diet: "veg",
    price: 210,
    inStock: true,
    stockCount: 40,
    prepTimeMinutes: 5,
  },
  {
    id: "itm-118",
    code: "#118",
    name: "Signature Berry Mojito",
    category: "Beverages & Shakes",
    diet: "drinks",
    price: 220,
    inStock: true,
    stockCount: 50,
    prepTimeMinutes: 6,
    description: "Muddled fresh mint, wild blackberries, lime chunks and sparkling soda",
  },
  {
    id: "itm-119",
    code: "#119",
    name: "Cold Brew Espresso Tonic",
    category: "Beverages & Shakes",
    diet: "drinks",
    price: 190,
    inStock: true,
    stockCount: 45,
    prepTimeMinutes: 5,
  },
  {
    id: "itm-120",
    code: "#120",
    name: "Royal Smoked Old Fashioned",
    category: "Bar & Cocktails",
    diet: "drinks",
    price: 550,
    inStock: true,
    stockCount: 30,
    prepTimeMinutes: 8,
    isChefSpecial: true,
  },
  {
    id: "itm-121",
    code: "#121",
    name: "Executive Lunch Combo (Veg)",
    category: "Combos",
    diet: "veg",
    price: 499,
    inStock: true,
    stockCount: 25,
    prepTimeMinutes: 12,
    description: "Dal Makhani, Paneer Lababdar, 2 Garlic Naan, Rice, Gulab Jamun and Beverage",
  },
  {
    id: "itm-122",
    code: "#122",
    name: "Royal Feast Combo (Non-Veg)",
    category: "Combos",
    diet: "non_veg",
    price: 649,
    inStock: true,
    stockCount: 20,
    prepTimeMinutes: 14,
    description: "Butter Chicken, Murgh Malai Tikka (2 pcs), 2 Butter Naan, Biryani, Dessert",
  },
];

export const MOCK_CUSTOMERS: CustomerProfile[] = [
  {
    id: "cust-1",
    name: "Vikram Sharma",
    phone: "+91 98201 44521",
    tier: "Platinum VIP",
    loyaltyPoints: 1480,
    visitCount: 34,
    lastVisit: "2 days ago",
    creditLimit: 50000,
    currentCredit: 0,
  },
  {
    id: "cust-2",
    name: "Pooja Malhotra",
    phone: "+91 98112 39012",
    tier: "Gold",
    loyaltyPoints: 620,
    visitCount: 16,
    lastVisit: "1 week ago",
    roomNumber: "Room 402",
  },
  {
    id: "cust-3",
    name: "Dr. Anish Reddy",
    phone: "+91 94405 88219",
    tier: "Gold",
    loyaltyPoints: 490,
    visitCount: 12,
    lastVisit: "Yesterday",
    roomNumber: "Room 312",
  },
  {
    id: "cust-4",
    name: "Sneha Kapoor",
    phone: "+91 99011 54320",
    tier: "Silver",
    loyaltyPoints: 150,
    visitCount: 4,
    lastVisit: "3 weeks ago",
  },
];

export const MOCK_HELD_BILLS: HeldBill[] = [
  {
    id: "held-1",
    billNumber: "RET-2026-9011",
    orderType: "dine_in",
    tableNumber: "T-04",
    guestCount: 2,
    captainName: "Kunal S.",
    heldAt: "18 mins ago",
    subtotal: 1420,
    tax: 71,
    grandTotal: 1491,
    notes: "Awaiting dessert decision",
    items: [
      {
        cartId: "c-h1",
        item: MOCK_MENU_ITEMS[0],
        quantity: 1,
        selectedModifiers: [],
        addedAt: "12:15 PM",
      },
      {
        cartId: "c-h2",
        item: MOCK_MENU_ITEMS[4],
        quantity: 1,
        selectedModifiers: [],
        addedAt: "12:17 PM",
      },
      {
        cartId: "c-h3",
        item: MOCK_MENU_ITEMS[8],
        quantity: 3,
        selectedModifiers: [],
        addedAt: "12:18 PM",
      },
    ],
  },
  {
    id: "held-2",
    billNumber: "RET-2026-9014",
    orderType: "dine_in",
    tableNumber: "T-08",
    guestCount: 6,
    captainName: "Rahul V.",
    heldAt: "32 mins ago",
    subtotal: 3840,
    tax: 192,
    grandTotal: 4032,
    customerName: "Pooja Malhotra",
    customerPhone: "+91 98112 39012",
    items: [
      {
        cartId: "c-h4",
        item: MOCK_MENU_ITEMS[1],
        quantity: 2,
        selectedModifiers: [],
        addedAt: "12:02 PM",
      },
      {
        cartId: "c-h5",
        item: MOCK_MENU_ITEMS[7],
        quantity: 2,
        selectedModifiers: [],
        addedAt: "12:05 PM",
      },
      {
        cartId: "c-h6",
        item: MOCK_MENU_ITEMS[10],
        quantity: 2,
        selectedModifiers: [],
        addedAt: "12:10 PM",
      },
    ],
  },
  {
    id: "held-3",
    billNumber: "RET-2026-9019",
    orderType: "takeaway",
    guestCount: 1,
    captainName: "Billing Counter 1",
    heldAt: "7 mins ago",
    subtotal: 860,
    tax: 43,
    grandTotal: 903,
    customerName: "Walk-in Guest",
    items: [
      {
        cartId: "c-h7",
        item: MOCK_MENU_ITEMS[20],
        quantity: 1,
        selectedModifiers: [],
        addedAt: "12:35 PM",
      },
      {
        cartId: "c-h8",
        item: MOCK_MENU_ITEMS[15],
        quantity: 1,
        selectedModifiers: [],
        addedAt: "12:36 PM",
      },
    ],
  },
];

export const MOCK_TABLES_LIST = [
  { id: "T-01", name: "Table 01", area: "Main Dining", capacity: 2, status: "Vacant" },
  { id: "T-02", name: "Table 02", area: "Main Dining", capacity: 4, status: "Occupied" },
  { id: "T-03", name: "Table 03", area: "Main Dining", capacity: 4, status: "Vacant" },
  { id: "T-04", name: "Table 04", area: "Main Dining", capacity: 2, status: "Billed" },
  { id: "T-05", name: "Table 05", area: "Main Dining", capacity: 6, status: "Occupied" },
  { id: "T-06", name: "Table 06", area: "Terrace Garden", capacity: 4, status: "Vacant" },
  { id: "T-07", name: "Table 07", area: "Terrace Garden", capacity: 4, status: "Occupied" },
  { id: "T-08", name: "Table 08", area: "Terrace Garden", capacity: 8, status: "Billed" },
  { id: "T-09", name: "Table 09", area: "Terrace Garden", capacity: 2, status: "Vacant" },
  { id: "T-10", name: "Table 10", area: "Bar Lounge", capacity: 2, status: "Occupied" },
  { id: "T-11", name: "Table 11", area: "Bar Lounge", capacity: 4, status: "Vacant" },
  { id: "T-12", name: "Table 12", area: "Bar Lounge", capacity: 4, status: "Occupied" },
  {
    id: "T-14",
    name: "Table 14",
    area: "Private Dining Room",
    capacity: 10,
    status: "Active Billing",
  },
  { id: "T-15", name: "Table 15", area: "Private Dining Room", capacity: 8, status: "Vacant" },
];
