import type {
  MarketingCampaign,
  WhatsAppTemplate,
  WhatsAppBroadcastRecord,
  LoyaltyTier,
  PromoVoucher,
  CustomerReview,
  CustomerSegment,
} from "@/types/posMarketing";

export const MOCK_CAMPAIGNS: MarketingCampaign[] = [
  {
    id: "cmp-01",
    name: "Weekend Chef's Tasting Special (Meta Ads)",
    channel: "meta_ads",
    objective: "Dine-In Bookings",
    status: "Active",
    budget: 15000,
    spent: 8400,
    reach: 48200,
    clicks: 1940,
    conversions: 142,
    revenueGenerated: 86400,
    startDate: "01 Sep 2026",
    endDate: "15 Sep 2026",
    tags: ["Fine Dining", "Weekend", "Instagram"],
  },
  {
    id: "cmp-02",
    name: "Google Local Search - 'Best Biryani & Kebabs Bandra'",
    channel: "google_local",
    objective: "Weekend Footfall",
    status: "Active",
    budget: 20000,
    spent: 14200,
    reach: 72000,
    clicks: 3450,
    conversions: 280,
    revenueGenerated: 142000,
    startDate: "20 Aug 2026",
    endDate: "30 Sep 2026",
    tags: ["Search Ads", "Bandra Local", "Maps"],
  },
  {
    id: "cmp-03",
    name: "VIP Platinum Club - Complimentary Wine & Dessert",
    channel: "whatsapp",
    objective: "Dine-In Bookings",
    status: "Active",
    budget: 5000,
    spent: 3200,
    reach: 2400,
    clicks: 890,
    conversions: 94,
    revenueGenerated: 98000,
    startDate: "28 Aug 2026",
    endDate: "10 Sep 2026",
    tags: ["VIP", "Retention", "WhatsApp Blast"],
  },
  {
    id: "cmp-04",
    name: "Corporate Lunch Hour 20% Off Promotion",
    channel: "sms",
    objective: "Online Orders",
    status: "Scheduled",
    budget: 8000,
    spent: 0,
    reach: 12000,
    clicks: 0,
    conversions: 0,
    revenueGenerated: 0,
    startDate: "10 Sep 2026",
    endDate: "25 Sep 2026",
    tags: ["Corporate", "Lunch", "Weekday"],
  },
  {
    id: "cmp-05",
    name: "Monsoon Sizzlers & Sangria Digital Display",
    channel: "in_store_display",
    objective: "Menu Launch",
    status: "Active",
    budget: 2500,
    spent: 2500,
    reach: 18500,
    clicks: 620,
    conversions: 110,
    revenueGenerated: 58000,
    startDate: "15 Aug 2026",
    endDate: "15 Sep 2026",
    tags: ["In-Store TV", "Sizzlers", "Upsell"],
  },
];

export const MOCK_WHATSAPP_TEMPLATES: WhatsAppTemplate[] = [
  {
    id: "tmpl-01",
    title: "Weekend Chef's Degustation Menu",
    category: "Special Offer",
    targetAudience: "VIP & Regular Diners",
    approvedStatus: "Approved",
    lastUsed: "Yesterday",
    bodyText:
      "Hello {{customer_name}}, craving an exquisite culinary evening? 🍷 Join us at Retrod this Friday & Saturday for our Chef's 7-course Tasting Degustation with paired reserve mocktails & wines. Reserve early & get a complimentary artisan dessert.",
    ctaText: "Book Table Now",
    ctaType: "url",
  },
  {
    id: "tmpl-02",
    title: "Birthday Celebration Gift (₹500 Voucher)",
    category: "Marketing",
    targetAudience: "Birthday in next 7 days",
    approvedStatus: "Approved",
    lastUsed: "3 days ago",
    bodyText:
      "Wishing you a very Happy Birthday Month, {{customer_name}}! 🎂 Celebrate your special day with loved ones at Retrod. Here is an exclusive ₹500 birthday gift voucher: *BDAY500*. Valid on Dine-in tables above ₹1,500.",
    ctaText: "Claim Birthday Treat",
    ctaType: "quick_reply",
  },
  {
    id: "tmpl-03",
    title: "We Miss You (Win-Back 30 Days Inactive)",
    category: "Special Offer",
    targetAudience: "Inactive > 30 days",
    approvedStatus: "Approved",
    lastUsed: "1 week ago",
    bodyText:
      "Hey {{customer_name}}, it has been a while since we served you your favorite {{favorite_dish}} at Retrod! 🍲 We have updated our menu with new monsoon specialties. Enjoy 20% off with code *COMEBACK20* on your next visit.",
    ctaText: "View New Menu",
    ctaType: "url",
  },
  {
    id: "tmpl-04",
    title: "Festival Celebration Feast Pre-Order",
    category: "Festival",
    targetAudience: "All Registered Guests",
    approvedStatus: "Approved",
    lastUsed: "2 weeks ago",
    bodyText:
      "Celebrate festive moments with Retrod's Gourmet Feast Platters & Handi Biryani! 🎉 Pre-book catering or a private dining room for your family and get 15% cashback points.",
    ctaText: "Pre-order Platters",
    ctaType: "url",
  },
];

export const MOCK_BROADCAST_HISTORY: WhatsAppBroadcastRecord[] = [
  {
    id: "bc-01",
    campaignTitle: "Friday Night Live Jazz & Sizzlers",
    templateName: "Weekend Chef's Degustation Menu",
    audienceName: "Platinum VIP Diners (380 contacts)",
    recipientCount: 380,
    deliveredCount: 374,
    readCount: 312,
    repliedCount: 48,
    sentAt: "Yesterday, 04:30 PM",
    status: "Delivered",
  },
  {
    id: "bc-02",
    campaignTitle: "September Birthday Perks",
    templateName: "Birthday Celebration Gift",
    audienceName: "Birthdays this week (64 contacts)",
    recipientCount: 64,
    deliveredCount: 64,
    readCount: 58,
    repliedCount: 19,
    sentAt: "01 Sep 2026, 11:00 AM",
    status: "Delivered",
  },
  {
    id: "bc-03",
    campaignTitle: "Win-Back 30-Day Lapsed Guests",
    templateName: "We Miss You (Win-Back)",
    audienceName: "Lapsed Diners (650 contacts)",
    recipientCount: 650,
    deliveredCount: 632,
    readCount: 480,
    repliedCount: 82,
    sentAt: "28 Aug 2026, 06:15 PM",
    status: "Delivered",
  },
];

export const MOCK_LOYALTY_TIERS: LoyaltyTier[] = [
  {
    id: "tier-1",
    name: "Silver",
    minPoints: 0,
    earnMultiplier: "1.0x (1 pt per ₹100)",
    benefits: [
      "1 point per ₹100 spent",
      "Birthday dessert on the house",
      "Digital receipt via WhatsApp",
    ],
    memberCount: 840,
    color: "text-slate-700 border-slate-300",
    badgeBg: "bg-slate-100 text-slate-800",
  },
  {
    id: "tier-2",
    name: "Gold",
    minPoints: 500,
    earnMultiplier: "1.5x (1.5 pts per ₹100)",
    benefits: [
      "1.5x points on weekend bills",
      "Priority table reservations",
      "Complimentary chef amuse-bouche",
      "10% off on takeaway orders",
    ],
    memberCount: 420,
    color: "text-amber-700 border-amber-300",
    badgeBg: "bg-amber-100 text-amber-900",
  },
  {
    id: "tier-3",
    name: "Platinum VIP",
    minPoints: 1200,
    earnMultiplier: "2.0x (2.0 pts per ₹100)",
    benefits: [
      "2x points on all dining bills",
      "Zero corkage charge on wines",
      "Dedicated Captain service",
      "Free private dining room upgrade",
      "Invite to quarterly Chef tasting table",
    ],
    memberCount: 220,
    color: "text-purple-700 border-purple-300",
    badgeBg: "bg-purple-100 text-purple-900",
  },
];

export const MOCK_PROMO_VOUCHERS: PromoVoucher[] = [
  {
    id: "vch-01",
    code: "RETROD10",
    title: "Flat 10% Welcome Discount",
    discountType: "percentage",
    discountValue: 10,
    minOrderValue: 800,
    maxDiscount: 300,
    validUntil: "31 Dec 2026",
    totalIssued: 1500,
    totalRedeemed: 642,
    status: "Active",
  },
  {
    id: "vch-02",
    code: "VIP20",
    title: "Platinum VIP 20% Privilege",
    discountType: "percentage",
    discountValue: 20,
    minOrderValue: 2000,
    maxDiscount: 1000,
    validUntil: "30 Nov 2026",
    totalIssued: 400,
    totalRedeemed: 218,
    status: "Active",
  },
  {
    id: "vch-03",
    code: "FLAT50",
    title: "Manager Special ₹50 Flat",
    discountType: "flat_amount",
    discountValue: 50,
    minOrderValue: 500,
    validUntil: "15 Oct 2026",
    totalIssued: 800,
    totalRedeemed: 390,
    status: "Active",
  },
  {
    id: "vch-04",
    code: "BDAY500",
    title: "Birthday Celebration ₹500 Gift",
    discountType: "flat_amount",
    discountValue: 500,
    minOrderValue: 1500,
    validUntil: "Ongoing",
    totalIssued: 320,
    totalRedeemed: 184,
    status: "Active",
  },
];

export const MOCK_REVIEWS: CustomerReview[] = [
  {
    id: "rev-01",
    platform: "google",
    customerName: "Aakash Mehta",
    rating: 5,
    reviewDate: "Yesterday",
    comment:
      "Hands down the best Butter Chicken and Garlic Naan in Bandra! Service by Steward Rahul was prompt and courteous. The ambiance is top notch.",
    sentiment: "Positive",
    dishMentioned: "Butter Chicken",
    replyStatus: "Replied",
    replyText:
      "Dear Aakash, thank you so much for the glowing review! We're thrilled you enjoyed the Butter Chicken and Rahul's hospitality. Looking forward to welcoming you back soon!",
    aiSuggestedReply:
      "Thank you Aakash! We take great pride in our slow-cooked Grandma recipe Butter Chicken. Will pass your compliments to Rahul!",
  },
  {
    id: "rev-02",
    platform: "zomato",
    customerName: "Priyanka Deshmukh",
    rating: 5,
    reviewDate: "2 days ago",
    comment:
      "Celebrated our anniversary at Retrod. The Chef surprised us with complimentary Sizzling Brownies and personalized mocktails. Wonderful memory!",
    sentiment: "Positive",
    dishMentioned: "Sizzling Brownie",
    replyStatus: "Pending",
    aiSuggestedReply:
      "Happy Anniversary Priyanka! We are honored to have been part of your special milestone and delighted that you loved the surprises. Cheers to many more celebrations!",
  },
  {
    id: "rev-03",
    platform: "tripadvisor",
    customerName: "Marcus Vance",
    rating: 4,
    reviewDate: "4 days ago",
    comment:
      "Great cocktails and Awadhi Gosht Biryani. Slightly crowded on Saturday evening so make sure to reserve beforehand. Worth the visit.",
    sentiment: "Positive",
    dishMentioned: "Gosht Biryani",
    replyStatus: "Pending",
    aiSuggestedReply:
      "Thank you Marcus for visiting us! We appreciate the tip for fellow diners on weekend table reservations. Glad the Awadhi Biryani hit the mark!",
  },
  {
    id: "rev-04",
    platform: "google",
    customerName: "Rohan Kulkarni",
    rating: 3,
    reviewDate: "1 week ago",
    comment:
      "Food quality was excellent as always, but our main course took about 25 minutes during peak dinner rush. Would appreciate quicker kitchen turnaround.",
    sentiment: "Neutral",
    dishMentioned: "Main Course",
    replyStatus: "Pending",
    aiSuggestedReply:
      "Dear Rohan, thank you for your candid feedback. We apologize for the wait time during the peak dinner rush. We are streamlining our kitchen line speed and would love to serve you a seamless dinner on your next visit.",
  },
];

export const MOCK_SEGMENTS: CustomerSegment[] = [
  {
    id: "seg-01",
    name: "Platinum & Gold VIPs",
    description: "High average spend (> ₹3,000) and visits at least twice a month",
    memberCount: 640,
    avgSpend: 3850,
    frequency: "2.4 visits / mo",
    criteria: "Total Spend > ₹25,000 OR Visits > 10 in 6 months",
    automatedFlow: "VIP concierge WhatsApp alert + Chef table invites",
    growthRate: "+14% this month",
  },
  {
    id: "seg-02",
    name: "Weekend Family Diners",
    description: "Large party sizes (4+ PAX) dining on Friday night, Saturday and Sunday",
    memberCount: 520,
    avgSpend: 2900,
    frequency: "1.5 visits / mo",
    criteria: "Average PAX ≥ 4 on Fri-Sun dinner slots",
    automatedFlow: "Friday 4 PM reminder with dessert perk for kids",
    growthRate: "+8% this month",
  },
  {
    id: "seg-03",
    name: "Lapsed Diners (30+ Days Inactive)",
    description: "Previously regular guests who haven't placed an order in the last 30 days",
    memberCount: 410,
    avgSpend: 1650,
    frequency: "0 visits / mo",
    criteria: "Days since last visit ≥ 30 days",
    automatedFlow: "Auto-trigger COMEBACK20 voucher on Day 30",
    growthRate: "-5% (Win-back active)",
  },
  {
    id: "seg-04",
    name: "Biryani & Kebab Enthusiasts",
    description: "Customers who order Awadhi Biryani or Tandoor items on 80%+ of visits",
    memberCount: 380,
    avgSpend: 1950,
    frequency: "1.8 visits / mo",
    criteria: "Item category history = 'Breads & Rice' or 'Starters'",
    automatedFlow: "Early access preview for new Biryani festival releases",
    growthRate: "+18% this month",
  },
];
