/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PosRouteImport } from './routes/pos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PosTablesRouteImport } from './routes/pos.tables'
import { Route as PosSettlementRouteImport } from './routes/pos.settlement'
import { Route as PosSettingsRouteImport } from './routes/pos.settings'
import { Route as PosRoomServiceRouteImport } from './routes/pos.room-service'
import { Route as PosReportsRouteImport } from './routes/pos.reports'
import { Route as PosOrdersRouteImport } from './routes/pos.orders'
import { Route as PosMenuRouteImport } from './routes/pos.menu'
import { Route as PosMarketingRouteImport } from './routes/pos.marketing'
import { Route as PosManagementRouteImport } from './routes/pos.management'
import { Route as PosKotRouteImport } from './routes/pos.kot'
import { Route as PosInventoryRouteImport } from './routes/pos.inventory'
import { Route as PosHelpRouteImport } from './routes/pos.help'
import { Route as PosCrmRouteImport } from './routes/pos.crm'
import { Route as PosBillingRouteImport } from './routes/pos.billing'
import { Route as PosAggregatorsRouteImport } from './routes/pos.aggregators'
import { Route as PosReportsOtherRouteImport } from './routes/pos.reports.other'
import { Route as PosReportsNotificationsRouteImport } from './routes/pos.reports.notifications'
import { Route as PosReportsDeliveryRouteImport } from './routes/pos.reports.delivery'
import { Route as PosReportsDayEndRouteImport } from './routes/pos.reports.day-end'
import { Route as PosOrdersOnlineRouteImport } from './routes/pos.orders.online'
import { Route as PosOrdersAllRouteImport } from './routes/pos.orders.all'
import { Route as PosMenuSpecialNotesRouteImport } from './routes/pos.menu.special-notes'
import { Route as PosMenuScheduleRouteImport } from './routes/pos.menu.schedule'
import { Route as PosMenuPhysicalRouteImport } from './routes/pos.menu.physical'
import { Route as PosMenuOnOffRouteImport } from './routes/pos.menu.on-off'
import { Route as PosMenuImagesRouteImport } from './routes/pos.menu.images'
import { Route as PosMenuCommissionRouteImport } from './routes/pos.menu.commission'
import { Route as PosManagementDeviceMappingRouteImport } from './routes/pos.management.device-mapping'
import { Route as PosManagementDataManagementRouteImport } from './routes/pos.management.data-management'
import { Route as PosManagementAuditTrailRouteImport } from './routes/pos.management.audit-trail'
import { Route as PosInventoryWastageRouteImport } from './routes/pos.inventory.wastage'
import { Route as PosInventoryTransferRouteImport } from './routes/pos.inventory.transfer'
import { Route as PosInventorySettingsRouteImport } from './routes/pos.inventory.settings'
import { Route as PosInventorySalesReturnRouteImport } from './routes/pos.inventory.sales-return'
import { Route as PosInventorySalesRouteImport } from './routes/pos.inventory.sales'
import { Route as PosInventoryReturnRouteImport } from './routes/pos.inventory.return'
import { Route as PosInventoryReportsRouteImport } from './routes/pos.inventory.reports'
import { Route as PosInventoryPurchaseRouteImport } from './routes/pos.inventory.purchase'
import { Route as PosInventoryProductionRouteImport } from './routes/pos.inventory.production'
import { Route as PosInventoryOrderRouteImport } from './routes/pos.inventory.order'
import { Route as PosInventoryMastersRouteImport } from './routes/pos.inventory.masters'
import { Route as PosInventoryClosingStockRouteImport } from './routes/pos.inventory.closing-stock'
import { Route as PosInventoryAvailableStockRouteImport } from './routes/pos.inventory.available-stock'
import { Route as PosManagementMarketplaceIndexRouteImport } from './routes/pos.management.marketplace.index'
import { Route as PosManagementUsersBillerGroupsRouteImport } from './routes/pos.management.users.biller-groups'
import { Route as PosManagementUsersBillerAppRouteImport } from './routes/pos.management.users.biller-app'
import { Route as PosManagementUsersAdminManagementRouteImport } from './routes/pos.management.users.admin-management'
import { Route as PosManagementUsersAdminGroupsRouteImport } from './routes/pos.management.users.admin-groups'
import { Route as PosManagementOutletKitchenRouteImport } from './routes/pos.management.outlet.kitchen'
import { Route as PosManagementOutletHoRouteImport } from './routes/pos.management.outlet.ho'
import { Route as PosManagementMarketplaceSettingsRouteImport } from './routes/pos.management.marketplace.settings'
import { Route as PosManagementLogsSupportRouteImport } from './routes/pos.management.logs.support'
import { Route as PosManagementLogsOnlineStoreRouteImport } from './routes/pos.management.logs.online-store'
import { Route as PosManagementConfigurationSubOrderTypeRouteImport } from './routes/pos.management.configuration.sub-order-type'
import { Route as PosManagementConfigurationOutletRouteImport } from './routes/pos.management.configuration.outlet'
import { Route as PosManagementConfigurationFloorPlanRouteImport } from './routes/pos.management.configuration.floor-plan'
import { Route as PosManagementConfigurationEmailTemplatesRouteImport } from './routes/pos.management.configuration.email-templates'
import { Route as PosManagementConfigurationDeliveryDistanceRouteImport } from './routes/pos.management.configuration.delivery-distance'
import { Route as PosManagementConfigurationAreaDeliveryChargesRouteImport } from './routes/pos.management.configuration.area-delivery-charges'
import { Route as PosManagementAccountingUtilityBillsRouteImport } from './routes/pos.management.accounting.utility-bills'
import { Route as PosManagementAccountingServicePaymentsRouteImport } from './routes/pos.management.accounting.service-payments'
import { Route as PosManagementAccountingOnlineReconciliationRouteImport } from './routes/pos.management.accounting.online-reconciliation'
import { Route as PosManagementAccountingLoansRouteImport } from './routes/pos.management.accounting.loans'
import { Route as PosManagementAccountingKycRouteImport } from './routes/pos.management.accounting.kyc'
import { Route as PosManagementAccountingGstRouteImport } from './routes/pos.management.accounting.gst'
import { Route as PosManagementAccountingExpensesRouteImport } from './routes/pos.management.accounting.expenses'
import { Route as PosManagementAccountingDenominationRouteImport } from './routes/pos.management.accounting.denomination'
import { Route as PosManagementAccountingBankDetailsRouteImport } from './routes/pos.management.accounting.bank-details'
import { Route as PosInventoryReportsStockSummaryRouteImport } from './routes/pos.inventory.reports.stock-summary'
import { Route as PosInventoryReportsOtherReportsRouteImport } from './routes/pos.inventory.reports.other-reports'
import { Route as PosInventoryReportsOrderwiseConsumptionRouteImport } from './routes/pos.inventory.reports.orderwise-consumption'
import { Route as PosInventoryProductionExecutionRouteImport } from './routes/pos.inventory.production.execution'
import { Route as PosInventoryProductionBarcodeRouteImport } from './routes/pos.inventory.production.barcode'
import { Route as PosInventoryMastersUnitsRouteImport } from './routes/pos.inventory.masters.units'
import { Route as PosInventoryMastersSuppliersRouteImport } from './routes/pos.inventory.masters.suppliers'
import { Route as PosInventoryMastersRecipesRouteImport } from './routes/pos.inventory.masters.recipes'
import { Route as PosInventoryMastersRawMaterialsRouteImport } from './routes/pos.inventory.masters.raw-materials'
import { Route as PosInventoryMastersPurchasePaymentsRouteImport } from './routes/pos.inventory.masters.purchase-payments'
import { Route as PosInventoryMastersInvoiceTemplatesRouteImport } from './routes/pos.inventory.masters.invoice-templates'
import { Route as PosManagementAccountingPaymentsWalletRouteImport } from './routes/pos.management.accounting.payments.wallet'
import { Route as PosManagementAccountingPaymentsInformationRouteImport } from './routes/pos.management.accounting.payments.information'

const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PosTablesRoute = PosTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => PosRoute,
} as any)
const PosSettlementRoute = PosSettlementRouteImport.update({
  id: '/settlement',
  path: '/settlement',
  getParentRoute: () => PosRoute,
} as any)
const PosSettingsRoute = PosSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PosRoute,
} as any)
const PosRoomServiceRoute = PosRoomServiceRouteImport.update({
  id: '/room-service',
  path: '/room-service',
  getParentRoute: () => PosRoute,
} as any)
const PosReportsRoute = PosReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => PosRoute,
} as any)
const PosOrdersRoute = PosOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => PosRoute,
} as any)
const PosMenuRoute = PosMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => PosRoute,
} as any)
const PosMarketingRoute = PosMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => PosRoute,
} as any)
const PosManagementRoute = PosManagementRouteImport.update({
  id: '/management',
  path: '/management',
  getParentRoute: () => PosRoute,
} as any)
const PosKotRoute = PosKotRouteImport.update({
  id: '/kot',
  path: '/kot',
  getParentRoute: () => PosRoute,
} as any)
const PosInventoryRoute = PosInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => PosRoute,
} as any)
const PosHelpRoute = PosHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => PosRoute,
} as any)
const PosCrmRoute = PosCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => PosRoute,
} as any)
const PosBillingRoute = PosBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => PosRoute,
} as any)
const PosAggregatorsRoute = PosAggregatorsRouteImport.update({
  id: '/aggregators',
  path: '/aggregators',
  getParentRoute: () => PosRoute,
} as any)
const PosReportsOtherRoute = PosReportsOtherRouteImport.update({
  id: '/other',
  path: '/other',
  getParentRoute: () => PosReportsRoute,
} as any)
const PosReportsNotificationsRoute = PosReportsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => PosReportsRoute,
} as any)
const PosReportsDeliveryRoute = PosReportsDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => PosReportsRoute,
} as any)
const PosReportsDayEndRoute = PosReportsDayEndRouteImport.update({
  id: '/day-end',
  path: '/day-end',
  getParentRoute: () => PosReportsRoute,
} as any)
const PosOrdersOnlineRoute = PosOrdersOnlineRouteImport.update({
  id: '/online',
  path: '/online',
  getParentRoute: () => PosOrdersRoute,
} as any)
const PosOrdersAllRoute = PosOrdersAllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => PosOrdersRoute,
} as any)
const PosMenuSpecialNotesRoute = PosMenuSpecialNotesRouteImport.update({
  id: '/special-notes',
  path: '/special-notes',
  getParentRoute: () => PosMenuRoute,
} as any)
const PosMenuScheduleRoute = PosMenuScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => PosMenuRoute,
} as any)
const PosMenuPhysicalRoute = PosMenuPhysicalRouteImport.update({
  id: '/physical',
  path: '/physical',
  getParentRoute: () => PosMenuRoute,
} as any)
const PosMenuOnOffRoute = PosMenuOnOffRouteImport.update({
  id: '/on-off',
  path: '/on-off',
  getParentRoute: () => PosMenuRoute,
} as any)
const PosMenuImagesRoute = PosMenuImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => PosMenuRoute,
} as any)
const PosMenuCommissionRoute = PosMenuCommissionRouteImport.update({
  id: '/commission',
  path: '/commission',
  getParentRoute: () => PosMenuRoute,
} as any)
const PosManagementDeviceMappingRoute =
  PosManagementDeviceMappingRouteImport.update({
    id: '/device-mapping',
    path: '/device-mapping',
    getParentRoute: () => PosManagementRoute,
  } as any)
const PosManagementDataManagementRoute =
  PosManagementDataManagementRouteImport.update({
    id: '/data-management',
    path: '/data-management',
    getParentRoute: () => PosManagementRoute,
  } as any)
const PosManagementAuditTrailRoute = PosManagementAuditTrailRouteImport.update({
  id: '/audit-trail',
  path: '/audit-trail',
  getParentRoute: () => PosManagementRoute,
} as any)
const PosInventoryWastageRoute = PosInventoryWastageRouteImport.update({
  id: '/wastage',
  path: '/wastage',
  getParentRoute: () => PosInventoryRoute,
} as any)
const PosInventoryTransferRoute = PosInventoryTransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => PosInventoryRoute,
} as any)
const PosInventorySettingsRoute = PosInventorySettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PosInventoryRoute,
} as any)
const PosInventorySalesReturnRoute = PosInventorySalesReturnRouteImport.update({
  id: '/sales-return',
  path: '/sales-return',
  getParentRoute: () => PosInventoryRoute,
} as any)
const PosInventorySalesRoute = PosInventorySalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => PosInventoryRoute,
} as any)
const PosInventoryReturnRoute = PosInventoryReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => PosInventoryRoute,
} as any)
const PosInventoryReportsRoute = PosInventoryReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => PosInventoryRoute,
} as any)
const PosInventoryPurchaseRoute = PosInventoryPurchaseRouteImport.update({
  id: '/purchase',
  path: '/purchase',
  getParentRoute: () => PosInventoryRoute,
} as any)
const PosInventoryProductionRoute = PosInventoryProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => PosInventoryRoute,
} as any)
const PosInventoryOrderRoute = PosInventoryOrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => PosInventoryRoute,
} as any)
const PosInventoryMastersRoute = PosInventoryMastersRouteImport.update({
  id: '/masters',
  path: '/masters',
  getParentRoute: () => PosInventoryRoute,
} as any)
const PosInventoryClosingStockRoute =
  PosInventoryClosingStockRouteImport.update({
    id: '/closing-stock',
    path: '/closing-stock',
    getParentRoute: () => PosInventoryRoute,
  } as any)
const PosInventoryAvailableStockRoute =
  PosInventoryAvailableStockRouteImport.update({
    id: '/available-stock',
    path: '/available-stock',
    getParentRoute: () => PosInventoryRoute,
  } as any)
const PosManagementMarketplaceIndexRoute =
  PosManagementMarketplaceIndexRouteImport.update({
    id: '/marketplace/',
    path: '/marketplace/',
    getParentRoute: () => PosManagementRoute,
  } as any)
const PosManagementUsersBillerGroupsRoute =
  PosManagementUsersBillerGroupsRouteImport.update({
    id: '/users/biller-groups',
    path: '/users/biller-groups',
    getParentRoute: () => PosManagementRoute,
  } as any)
const PosManagementUsersBillerAppRoute =
  PosManagementUsersBillerAppRouteImport.update({
    id: '/users/biller-app',
    path: '/users/biller-app',
    getParentRoute: () => PosManagementRoute,
  } as any)
const PosManagementUsersAdminManagementRoute =
  PosManagementUsersAdminManagementRouteImport.update({
    id: '/users/admin-management',
    path: '/users/admin-management',
    getParentRoute: () => PosManagementRoute,
  } as any)
const PosManagementUsersAdminGroupsRoute =
  PosManagementUsersAdminGroupsRouteImport.update({
    id: '/users/admin-groups',
    path: '/users/admin-groups',
    getParentRoute: () => PosManagementRoute,
  } as any)
const PosManagementOutletKitchenRoute =
  PosManagementOutletKitchenRouteImport.update({
    id: '/outlet/kitchen',
    path: '/outlet/kitchen',
    getParentRoute: () => PosManagementRoute,
  } as any)
const PosManagementOutletHoRoute = PosManagementOutletHoRouteImport.update({
  id: '/outlet/ho',
  path: '/outlet/ho',
  getParentRoute: () => PosManagementRoute,
} as any)
const PosManagementMarketplaceSettingsRoute =
  PosManagementMarketplaceSettingsRouteImport.update({
    id: '/marketplace/settings',
    path: '/marketplace/settings',
    getParentRoute: () => PosManagementRoute,
  } as any)
const PosManagementLogsSupportRoute =
  PosManagementLogsSupportRouteImport.update({
    id: '/logs/support',
    path: '/logs/support',
    getParentRoute: () => PosManagementRoute,
  } as any)
const PosManagementLogsOnlineStoreRoute =
  PosManagementLogsOnlineStoreRouteImport.update({
    id: '/logs/online-store',
    path: '/logs/online-store',
    getParentRoute: () => PosManagementRoute,
  } as any)
const PosManagementConfigurationSubOrderTypeRoute =
  PosManagementConfigurationSubOrderTypeRouteImport.update({
    id: '/configuration/sub-order-type',
    path: '/configuration/sub-order-type',
    getParentRoute: () => PosManagementRoute,
  } as any)
const PosManagementConfigurationOutletRoute =
  PosManagementConfigurationOutletRouteImport.update({
    id: '/configuration/outlet',
    path: '/configuration/outlet',
    getParentRoute: () => PosManagementRoute,
  } as any)
const PosManagementConfigurationFloorPlanRoute =
  PosManagementConfigurationFloorPlanRouteImport.update({
    id: '/configuration/floor-plan',
    path: '/configuration/floor-plan',
    getParentRoute: () => PosManagementRoute,
  } as any)
const PosManagementConfigurationEmailTemplatesRoute =
  PosManagementConfigurationEmailTemplatesRouteImport.update({
    id: '/configuration/email-templates',
    path: '/configuration/email-templates',
    getParentRoute: () => PosManagementRoute,
  } as any)
const PosManagementConfigurationDeliveryDistanceRoute =
  PosManagementConfigurationDeliveryDistanceRouteImport.update({
    id: '/configuration/delivery-distance',
    path: '/configuration/delivery-distance',
    getParentRoute: () => PosManagementRoute,
  } as any)
const PosManagementConfigurationAreaDeliveryChargesRoute =
  PosManagementConfigurationAreaDeliveryChargesRouteImport.update({
    id: '/configuration/area-delivery-charges',
    path: '/configuration/area-delivery-charges',
    getParentRoute: () => PosManagementRoute,
  } as any)
const PosManagementAccountingUtilityBillsRoute =
  PosManagementAccountingUtilityBillsRouteImport.update({
    id: '/accounting/utility-bills',
    path: '/accounting/utility-bills',
    getParentRoute: () => PosManagementRoute,
  } as any)
const PosManagementAccountingServicePaymentsRoute =
  PosManagementAccountingServicePaymentsRouteImport.update({
    id: '/accounting/service-payments',
    path: '/accounting/service-payments',
    getParentRoute: () => PosManagementRoute,
  } as any)
const PosManagementAccountingOnlineReconciliationRoute =
  PosManagementAccountingOnlineReconciliationRouteImport.update({
    id: '/accounting/online-reconciliation',
    path: '/accounting/online-reconciliation',
    getParentRoute: () => PosManagementRoute,
  } as any)
const PosManagementAccountingLoansRoute =
  PosManagementAccountingLoansRouteImport.update({
    id: '/accounting/loans',
    path: '/accounting/loans',
    getParentRoute: () => PosManagementRoute,
  } as any)
const PosManagementAccountingKycRoute =
  PosManagementAccountingKycRouteImport.update({
    id: '/accounting/kyc',
    path: '/accounting/kyc',
    getParentRoute: () => PosManagementRoute,
  } as any)
const PosManagementAccountingGstRoute =
  PosManagementAccountingGstRouteImport.update({
    id: '/accounting/gst',
    path: '/accounting/gst',
    getParentRoute: () => PosManagementRoute,
  } as any)
const PosManagementAccountingExpensesRoute =
  PosManagementAccountingExpensesRouteImport.update({
    id: '/accounting/expenses',
    path: '/accounting/expenses',
    getParentRoute: () => PosManagementRoute,
  } as any)
const PosManagementAccountingDenominationRoute =
  PosManagementAccountingDenominationRouteImport.update({
    id: '/accounting/denomination',
    path: '/accounting/denomination',
    getParentRoute: () => PosManagementRoute,
  } as any)
const PosManagementAccountingBankDetailsRoute =
  PosManagementAccountingBankDetailsRouteImport.update({
    id: '/accounting/bank-details',
    path: '/accounting/bank-details',
    getParentRoute: () => PosManagementRoute,
  } as any)
const PosInventoryReportsStockSummaryRoute =
  PosInventoryReportsStockSummaryRouteImport.update({
    id: '/stock-summary',
    path: '/stock-summary',
    getParentRoute: () => PosInventoryReportsRoute,
  } as any)
const PosInventoryReportsOtherReportsRoute =
  PosInventoryReportsOtherReportsRouteImport.update({
    id: '/other-reports',
    path: '/other-reports',
    getParentRoute: () => PosInventoryReportsRoute,
  } as any)
const PosInventoryReportsOrderwiseConsumptionRoute =
  PosInventoryReportsOrderwiseConsumptionRouteImport.update({
    id: '/orderwise-consumption',
    path: '/orderwise-consumption',
    getParentRoute: () => PosInventoryReportsRoute,
  } as any)
const PosInventoryProductionExecutionRoute =
  PosInventoryProductionExecutionRouteImport.update({
    id: '/execution',
    path: '/execution',
    getParentRoute: () => PosInventoryProductionRoute,
  } as any)
const PosInventoryProductionBarcodeRoute =
  PosInventoryProductionBarcodeRouteImport.update({
    id: '/barcode',
    path: '/barcode',
    getParentRoute: () => PosInventoryProductionRoute,
  } as any)
const PosInventoryMastersUnitsRoute =
  PosInventoryMastersUnitsRouteImport.update({
    id: '/units',
    path: '/units',
    getParentRoute: () => PosInventoryMastersRoute,
  } as any)
const PosInventoryMastersSuppliersRoute =
  PosInventoryMastersSuppliersRouteImport.update({
    id: '/suppliers',
    path: '/suppliers',
    getParentRoute: () => PosInventoryMastersRoute,
  } as any)
const PosInventoryMastersRecipesRoute =
  PosInventoryMastersRecipesRouteImport.update({
    id: '/recipes',
    path: '/recipes',
    getParentRoute: () => PosInventoryMastersRoute,
  } as any)
const PosInventoryMastersRawMaterialsRoute =
  PosInventoryMastersRawMaterialsRouteImport.update({
    id: '/raw-materials',
    path: '/raw-materials',
    getParentRoute: () => PosInventoryMastersRoute,
  } as any)
const PosInventoryMastersPurchasePaymentsRoute =
  PosInventoryMastersPurchasePaymentsRouteImport.update({
    id: '/purchase-payments',
    path: '/purchase-payments',
    getParentRoute: () => PosInventoryMastersRoute,
  } as any)
const PosInventoryMastersInvoiceTemplatesRoute =
  PosInventoryMastersInvoiceTemplatesRouteImport.update({
    id: '/invoice-templates',
    path: '/invoice-templates',
    getParentRoute: () => PosInventoryMastersRoute,
  } as any)
const PosManagementAccountingPaymentsWalletRoute =
  PosManagementAccountingPaymentsWalletRouteImport.update({
    id: '/accounting/payments/wallet',
    path: '/accounting/payments/wallet',
    getParentRoute: () => PosManagementRoute,
  } as any)
const PosManagementAccountingPaymentsInformationRoute =
  PosManagementAccountingPaymentsInformationRouteImport.update({
    id: '/accounting/payments/information',
    path: '/accounting/payments/information',
    getParentRoute: () => PosManagementRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pos': typeof PosRouteWithChildren
  '/pos/aggregators': typeof PosAggregatorsRoute
  '/pos/billing': typeof PosBillingRoute
  '/pos/crm': typeof PosCrmRoute
  '/pos/help': typeof PosHelpRoute
  '/pos/inventory': typeof PosInventoryRouteWithChildren
  '/pos/kot': typeof PosKotRoute
  '/pos/management': typeof PosManagementRouteWithChildren
  '/pos/marketing': typeof PosMarketingRoute
  '/pos/menu': typeof PosMenuRouteWithChildren
  '/pos/orders': typeof PosOrdersRouteWithChildren
  '/pos/reports': typeof PosReportsRouteWithChildren
  '/pos/room-service': typeof PosRoomServiceRoute
  '/pos/settings': typeof PosSettingsRoute
  '/pos/settlement': typeof PosSettlementRoute
  '/pos/tables': typeof PosTablesRoute
  '/pos/inventory/available-stock': typeof PosInventoryAvailableStockRoute
  '/pos/inventory/closing-stock': typeof PosInventoryClosingStockRoute
  '/pos/inventory/masters': typeof PosInventoryMastersRouteWithChildren
  '/pos/inventory/order': typeof PosInventoryOrderRoute
  '/pos/inventory/production': typeof PosInventoryProductionRouteWithChildren
  '/pos/inventory/purchase': typeof PosInventoryPurchaseRoute
  '/pos/inventory/reports': typeof PosInventoryReportsRouteWithChildren
  '/pos/inventory/return': typeof PosInventoryReturnRoute
  '/pos/inventory/sales': typeof PosInventorySalesRoute
  '/pos/inventory/sales-return': typeof PosInventorySalesReturnRoute
  '/pos/inventory/settings': typeof PosInventorySettingsRoute
  '/pos/inventory/transfer': typeof PosInventoryTransferRoute
  '/pos/inventory/wastage': typeof PosInventoryWastageRoute
  '/pos/management/audit-trail': typeof PosManagementAuditTrailRoute
  '/pos/management/data-management': typeof PosManagementDataManagementRoute
  '/pos/management/device-mapping': typeof PosManagementDeviceMappingRoute
  '/pos/menu/commission': typeof PosMenuCommissionRoute
  '/pos/menu/images': typeof PosMenuImagesRoute
  '/pos/menu/on-off': typeof PosMenuOnOffRoute
  '/pos/menu/physical': typeof PosMenuPhysicalRoute
  '/pos/menu/schedule': typeof PosMenuScheduleRoute
  '/pos/menu/special-notes': typeof PosMenuSpecialNotesRoute
  '/pos/orders/all': typeof PosOrdersAllRoute
  '/pos/orders/online': typeof PosOrdersOnlineRoute
  '/pos/reports/day-end': typeof PosReportsDayEndRoute
  '/pos/reports/delivery': typeof PosReportsDeliveryRoute
  '/pos/reports/notifications': typeof PosReportsNotificationsRoute
  '/pos/reports/other': typeof PosReportsOtherRoute
  '/pos/inventory/masters/invoice-templates': typeof PosInventoryMastersInvoiceTemplatesRoute
  '/pos/inventory/masters/purchase-payments': typeof PosInventoryMastersPurchasePaymentsRoute
  '/pos/inventory/masters/raw-materials': typeof PosInventoryMastersRawMaterialsRoute
  '/pos/inventory/masters/recipes': typeof PosInventoryMastersRecipesRoute
  '/pos/inventory/masters/suppliers': typeof PosInventoryMastersSuppliersRoute
  '/pos/inventory/masters/units': typeof PosInventoryMastersUnitsRoute
  '/pos/inventory/production/barcode': typeof PosInventoryProductionBarcodeRoute
  '/pos/inventory/production/execution': typeof PosInventoryProductionExecutionRoute
  '/pos/inventory/reports/orderwise-consumption': typeof PosInventoryReportsOrderwiseConsumptionRoute
  '/pos/inventory/reports/other-reports': typeof PosInventoryReportsOtherReportsRoute
  '/pos/inventory/reports/stock-summary': typeof PosInventoryReportsStockSummaryRoute
  '/pos/management/accounting/bank-details': typeof PosManagementAccountingBankDetailsRoute
  '/pos/management/accounting/denomination': typeof PosManagementAccountingDenominationRoute
  '/pos/management/accounting/expenses': typeof PosManagementAccountingExpensesRoute
  '/pos/management/accounting/gst': typeof PosManagementAccountingGstRoute
  '/pos/management/accounting/kyc': typeof PosManagementAccountingKycRoute
  '/pos/management/accounting/loans': typeof PosManagementAccountingLoansRoute
  '/pos/management/accounting/online-reconciliation': typeof PosManagementAccountingOnlineReconciliationRoute
  '/pos/management/accounting/service-payments': typeof PosManagementAccountingServicePaymentsRoute
  '/pos/management/accounting/utility-bills': typeof PosManagementAccountingUtilityBillsRoute
  '/pos/management/configuration/area-delivery-charges': typeof PosManagementConfigurationAreaDeliveryChargesRoute
  '/pos/management/configuration/delivery-distance': typeof PosManagementConfigurationDeliveryDistanceRoute
  '/pos/management/configuration/email-templates': typeof PosManagementConfigurationEmailTemplatesRoute
  '/pos/management/configuration/floor-plan': typeof PosManagementConfigurationFloorPlanRoute
  '/pos/management/configuration/outlet': typeof PosManagementConfigurationOutletRoute
  '/pos/management/configuration/sub-order-type': typeof PosManagementConfigurationSubOrderTypeRoute
  '/pos/management/logs/online-store': typeof PosManagementLogsOnlineStoreRoute
  '/pos/management/logs/support': typeof PosManagementLogsSupportRoute
  '/pos/management/marketplace/settings': typeof PosManagementMarketplaceSettingsRoute
  '/pos/management/outlet/ho': typeof PosManagementOutletHoRoute
  '/pos/management/outlet/kitchen': typeof PosManagementOutletKitchenRoute
  '/pos/management/users/admin-groups': typeof PosManagementUsersAdminGroupsRoute
  '/pos/management/users/admin-management': typeof PosManagementUsersAdminManagementRoute
  '/pos/management/users/biller-app': typeof PosManagementUsersBillerAppRoute
  '/pos/management/users/biller-groups': typeof PosManagementUsersBillerGroupsRoute
  '/pos/management/marketplace/': typeof PosManagementMarketplaceIndexRoute
  '/pos/management/accounting/payments/information': typeof PosManagementAccountingPaymentsInformationRoute
  '/pos/management/accounting/payments/wallet': typeof PosManagementAccountingPaymentsWalletRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pos': typeof PosRouteWithChildren
  '/pos/aggregators': typeof PosAggregatorsRoute
  '/pos/billing': typeof PosBillingRoute
  '/pos/crm': typeof PosCrmRoute
  '/pos/help': typeof PosHelpRoute
  '/pos/inventory': typeof PosInventoryRouteWithChildren
  '/pos/kot': typeof PosKotRoute
  '/pos/management': typeof PosManagementRouteWithChildren
  '/pos/marketing': typeof PosMarketingRoute
  '/pos/menu': typeof PosMenuRouteWithChildren
  '/pos/orders': typeof PosOrdersRouteWithChildren
  '/pos/reports': typeof PosReportsRouteWithChildren
  '/pos/room-service': typeof PosRoomServiceRoute
  '/pos/settings': typeof PosSettingsRoute
  '/pos/settlement': typeof PosSettlementRoute
  '/pos/tables': typeof PosTablesRoute
  '/pos/inventory/available-stock': typeof PosInventoryAvailableStockRoute
  '/pos/inventory/closing-stock': typeof PosInventoryClosingStockRoute
  '/pos/inventory/masters': typeof PosInventoryMastersRouteWithChildren
  '/pos/inventory/order': typeof PosInventoryOrderRoute
  '/pos/inventory/production': typeof PosInventoryProductionRouteWithChildren
  '/pos/inventory/purchase': typeof PosInventoryPurchaseRoute
  '/pos/inventory/reports': typeof PosInventoryReportsRouteWithChildren
  '/pos/inventory/return': typeof PosInventoryReturnRoute
  '/pos/inventory/sales': typeof PosInventorySalesRoute
  '/pos/inventory/sales-return': typeof PosInventorySalesReturnRoute
  '/pos/inventory/settings': typeof PosInventorySettingsRoute
  '/pos/inventory/transfer': typeof PosInventoryTransferRoute
  '/pos/inventory/wastage': typeof PosInventoryWastageRoute
  '/pos/management/audit-trail': typeof PosManagementAuditTrailRoute
  '/pos/management/data-management': typeof PosManagementDataManagementRoute
  '/pos/management/device-mapping': typeof PosManagementDeviceMappingRoute
  '/pos/menu/commission': typeof PosMenuCommissionRoute
  '/pos/menu/images': typeof PosMenuImagesRoute
  '/pos/menu/on-off': typeof PosMenuOnOffRoute
  '/pos/menu/physical': typeof PosMenuPhysicalRoute
  '/pos/menu/schedule': typeof PosMenuScheduleRoute
  '/pos/menu/special-notes': typeof PosMenuSpecialNotesRoute
  '/pos/orders/all': typeof PosOrdersAllRoute
  '/pos/orders/online': typeof PosOrdersOnlineRoute
  '/pos/reports/day-end': typeof PosReportsDayEndRoute
  '/pos/reports/delivery': typeof PosReportsDeliveryRoute
  '/pos/reports/notifications': typeof PosReportsNotificationsRoute
  '/pos/reports/other': typeof PosReportsOtherRoute
  '/pos/inventory/masters/invoice-templates': typeof PosInventoryMastersInvoiceTemplatesRoute
  '/pos/inventory/masters/purchase-payments': typeof PosInventoryMastersPurchasePaymentsRoute
  '/pos/inventory/masters/raw-materials': typeof PosInventoryMastersRawMaterialsRoute
  '/pos/inventory/masters/recipes': typeof PosInventoryMastersRecipesRoute
  '/pos/inventory/masters/suppliers': typeof PosInventoryMastersSuppliersRoute
  '/pos/inventory/masters/units': typeof PosInventoryMastersUnitsRoute
  '/pos/inventory/production/barcode': typeof PosInventoryProductionBarcodeRoute
  '/pos/inventory/production/execution': typeof PosInventoryProductionExecutionRoute
  '/pos/inventory/reports/orderwise-consumption': typeof PosInventoryReportsOrderwiseConsumptionRoute
  '/pos/inventory/reports/other-reports': typeof PosInventoryReportsOtherReportsRoute
  '/pos/inventory/reports/stock-summary': typeof PosInventoryReportsStockSummaryRoute
  '/pos/management/accounting/bank-details': typeof PosManagementAccountingBankDetailsRoute
  '/pos/management/accounting/denomination': typeof PosManagementAccountingDenominationRoute
  '/pos/management/accounting/expenses': typeof PosManagementAccountingExpensesRoute
  '/pos/management/accounting/gst': typeof PosManagementAccountingGstRoute
  '/pos/management/accounting/kyc': typeof PosManagementAccountingKycRoute
  '/pos/management/accounting/loans': typeof PosManagementAccountingLoansRoute
  '/pos/management/accounting/online-reconciliation': typeof PosManagementAccountingOnlineReconciliationRoute
  '/pos/management/accounting/service-payments': typeof PosManagementAccountingServicePaymentsRoute
  '/pos/management/accounting/utility-bills': typeof PosManagementAccountingUtilityBillsRoute
  '/pos/management/configuration/area-delivery-charges': typeof PosManagementConfigurationAreaDeliveryChargesRoute
  '/pos/management/configuration/delivery-distance': typeof PosManagementConfigurationDeliveryDistanceRoute
  '/pos/management/configuration/email-templates': typeof PosManagementConfigurationEmailTemplatesRoute
  '/pos/management/configuration/floor-plan': typeof PosManagementConfigurationFloorPlanRoute
  '/pos/management/configuration/outlet': typeof PosManagementConfigurationOutletRoute
  '/pos/management/configuration/sub-order-type': typeof PosManagementConfigurationSubOrderTypeRoute
  '/pos/management/logs/online-store': typeof PosManagementLogsOnlineStoreRoute
  '/pos/management/logs/support': typeof PosManagementLogsSupportRoute
  '/pos/management/marketplace/settings': typeof PosManagementMarketplaceSettingsRoute
  '/pos/management/outlet/ho': typeof PosManagementOutletHoRoute
  '/pos/management/outlet/kitchen': typeof PosManagementOutletKitchenRoute
  '/pos/management/users/admin-groups': typeof PosManagementUsersAdminGroupsRoute
  '/pos/management/users/admin-management': typeof PosManagementUsersAdminManagementRoute
  '/pos/management/users/biller-app': typeof PosManagementUsersBillerAppRoute
  '/pos/management/users/biller-groups': typeof PosManagementUsersBillerGroupsRoute
  '/pos/management/marketplace': typeof PosManagementMarketplaceIndexRoute
  '/pos/management/accounting/payments/information': typeof PosManagementAccountingPaymentsInformationRoute
  '/pos/management/accounting/payments/wallet': typeof PosManagementAccountingPaymentsWalletRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pos': typeof PosRouteWithChildren
  '/pos/aggregators': typeof PosAggregatorsRoute
  '/pos/billing': typeof PosBillingRoute
  '/pos/crm': typeof PosCrmRoute
  '/pos/help': typeof PosHelpRoute
  '/pos/inventory': typeof PosInventoryRouteWithChildren
  '/pos/kot': typeof PosKotRoute
  '/pos/management': typeof PosManagementRouteWithChildren
  '/pos/marketing': typeof PosMarketingRoute
  '/pos/menu': typeof PosMenuRouteWithChildren
  '/pos/orders': typeof PosOrdersRouteWithChildren
  '/pos/reports': typeof PosReportsRouteWithChildren
  '/pos/room-service': typeof PosRoomServiceRoute
  '/pos/settings': typeof PosSettingsRoute
  '/pos/settlement': typeof PosSettlementRoute
  '/pos/tables': typeof PosTablesRoute
  '/pos/inventory/available-stock': typeof PosInventoryAvailableStockRoute
  '/pos/inventory/closing-stock': typeof PosInventoryClosingStockRoute
  '/pos/inventory/masters': typeof PosInventoryMastersRouteWithChildren
  '/pos/inventory/order': typeof PosInventoryOrderRoute
  '/pos/inventory/production': typeof PosInventoryProductionRouteWithChildren
  '/pos/inventory/purchase': typeof PosInventoryPurchaseRoute
  '/pos/inventory/reports': typeof PosInventoryReportsRouteWithChildren
  '/pos/inventory/return': typeof PosInventoryReturnRoute
  '/pos/inventory/sales': typeof PosInventorySalesRoute
  '/pos/inventory/sales-return': typeof PosInventorySalesReturnRoute
  '/pos/inventory/settings': typeof PosInventorySettingsRoute
  '/pos/inventory/transfer': typeof PosInventoryTransferRoute
  '/pos/inventory/wastage': typeof PosInventoryWastageRoute
  '/pos/management/audit-trail': typeof PosManagementAuditTrailRoute
  '/pos/management/data-management': typeof PosManagementDataManagementRoute
  '/pos/management/device-mapping': typeof PosManagementDeviceMappingRoute
  '/pos/menu/commission': typeof PosMenuCommissionRoute
  '/pos/menu/images': typeof PosMenuImagesRoute
  '/pos/menu/on-off': typeof PosMenuOnOffRoute
  '/pos/menu/physical': typeof PosMenuPhysicalRoute
  '/pos/menu/schedule': typeof PosMenuScheduleRoute
  '/pos/menu/special-notes': typeof PosMenuSpecialNotesRoute
  '/pos/orders/all': typeof PosOrdersAllRoute
  '/pos/orders/online': typeof PosOrdersOnlineRoute
  '/pos/reports/day-end': typeof PosReportsDayEndRoute
  '/pos/reports/delivery': typeof PosReportsDeliveryRoute
  '/pos/reports/notifications': typeof PosReportsNotificationsRoute
  '/pos/reports/other': typeof PosReportsOtherRoute
  '/pos/inventory/masters/invoice-templates': typeof PosInventoryMastersInvoiceTemplatesRoute
  '/pos/inventory/masters/purchase-payments': typeof PosInventoryMastersPurchasePaymentsRoute
  '/pos/inventory/masters/raw-materials': typeof PosInventoryMastersRawMaterialsRoute
  '/pos/inventory/masters/recipes': typeof PosInventoryMastersRecipesRoute
  '/pos/inventory/masters/suppliers': typeof PosInventoryMastersSuppliersRoute
  '/pos/inventory/masters/units': typeof PosInventoryMastersUnitsRoute
  '/pos/inventory/production/barcode': typeof PosInventoryProductionBarcodeRoute
  '/pos/inventory/production/execution': typeof PosInventoryProductionExecutionRoute
  '/pos/inventory/reports/orderwise-consumption': typeof PosInventoryReportsOrderwiseConsumptionRoute
  '/pos/inventory/reports/other-reports': typeof PosInventoryReportsOtherReportsRoute
  '/pos/inventory/reports/stock-summary': typeof PosInventoryReportsStockSummaryRoute
  '/pos/management/accounting/bank-details': typeof PosManagementAccountingBankDetailsRoute
  '/pos/management/accounting/denomination': typeof PosManagementAccountingDenominationRoute
  '/pos/management/accounting/expenses': typeof PosManagementAccountingExpensesRoute
  '/pos/management/accounting/gst': typeof PosManagementAccountingGstRoute
  '/pos/management/accounting/kyc': typeof PosManagementAccountingKycRoute
  '/pos/management/accounting/loans': typeof PosManagementAccountingLoansRoute
  '/pos/management/accounting/online-reconciliation': typeof PosManagementAccountingOnlineReconciliationRoute
  '/pos/management/accounting/service-payments': typeof PosManagementAccountingServicePaymentsRoute
  '/pos/management/accounting/utility-bills': typeof PosManagementAccountingUtilityBillsRoute
  '/pos/management/configuration/area-delivery-charges': typeof PosManagementConfigurationAreaDeliveryChargesRoute
  '/pos/management/configuration/delivery-distance': typeof PosManagementConfigurationDeliveryDistanceRoute
  '/pos/management/configuration/email-templates': typeof PosManagementConfigurationEmailTemplatesRoute
  '/pos/management/configuration/floor-plan': typeof PosManagementConfigurationFloorPlanRoute
  '/pos/management/configuration/outlet': typeof PosManagementConfigurationOutletRoute
  '/pos/management/configuration/sub-order-type': typeof PosManagementConfigurationSubOrderTypeRoute
  '/pos/management/logs/online-store': typeof PosManagementLogsOnlineStoreRoute
  '/pos/management/logs/support': typeof PosManagementLogsSupportRoute
  '/pos/management/marketplace/settings': typeof PosManagementMarketplaceSettingsRoute
  '/pos/management/outlet/ho': typeof PosManagementOutletHoRoute
  '/pos/management/outlet/kitchen': typeof PosManagementOutletKitchenRoute
  '/pos/management/users/admin-groups': typeof PosManagementUsersAdminGroupsRoute
  '/pos/management/users/admin-management': typeof PosManagementUsersAdminManagementRoute
  '/pos/management/users/biller-app': typeof PosManagementUsersBillerAppRoute
  '/pos/management/users/biller-groups': typeof PosManagementUsersBillerGroupsRoute
  '/pos/management/marketplace/': typeof PosManagementMarketplaceIndexRoute
  '/pos/management/accounting/payments/information': typeof PosManagementAccountingPaymentsInformationRoute
  '/pos/management/accounting/payments/wallet': typeof PosManagementAccountingPaymentsWalletRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pos'
    | '/pos/aggregators'
    | '/pos/billing'
    | '/pos/crm'
    | '/pos/help'
    | '/pos/inventory'
    | '/pos/kot'
    | '/pos/management'
    | '/pos/marketing'
    | '/pos/menu'
    | '/pos/orders'
    | '/pos/reports'
    | '/pos/room-service'
    | '/pos/settings'
    | '/pos/settlement'
    | '/pos/tables'
    | '/pos/inventory/available-stock'
    | '/pos/inventory/closing-stock'
    | '/pos/inventory/masters'
    | '/pos/inventory/order'
    | '/pos/inventory/production'
    | '/pos/inventory/purchase'
    | '/pos/inventory/reports'
    | '/pos/inventory/return'
    | '/pos/inventory/sales'
    | '/pos/inventory/sales-return'
    | '/pos/inventory/settings'
    | '/pos/inventory/transfer'
    | '/pos/inventory/wastage'
    | '/pos/management/audit-trail'
    | '/pos/management/data-management'
    | '/pos/management/device-mapping'
    | '/pos/menu/commission'
    | '/pos/menu/images'
    | '/pos/menu/on-off'
    | '/pos/menu/physical'
    | '/pos/menu/schedule'
    | '/pos/menu/special-notes'
    | '/pos/orders/all'
    | '/pos/orders/online'
    | '/pos/reports/day-end'
    | '/pos/reports/delivery'
    | '/pos/reports/notifications'
    | '/pos/reports/other'
    | '/pos/inventory/masters/invoice-templates'
    | '/pos/inventory/masters/purchase-payments'
    | '/pos/inventory/masters/raw-materials'
    | '/pos/inventory/masters/recipes'
    | '/pos/inventory/masters/suppliers'
    | '/pos/inventory/masters/units'
    | '/pos/inventory/production/barcode'
    | '/pos/inventory/production/execution'
    | '/pos/inventory/reports/orderwise-consumption'
    | '/pos/inventory/reports/other-reports'
    | '/pos/inventory/reports/stock-summary'
    | '/pos/management/accounting/bank-details'
    | '/pos/management/accounting/denomination'
    | '/pos/management/accounting/expenses'
    | '/pos/management/accounting/gst'
    | '/pos/management/accounting/kyc'
    | '/pos/management/accounting/loans'
    | '/pos/management/accounting/online-reconciliation'
    | '/pos/management/accounting/service-payments'
    | '/pos/management/accounting/utility-bills'
    | '/pos/management/configuration/area-delivery-charges'
    | '/pos/management/configuration/delivery-distance'
    | '/pos/management/configuration/email-templates'
    | '/pos/management/configuration/floor-plan'
    | '/pos/management/configuration/outlet'
    | '/pos/management/configuration/sub-order-type'
    | '/pos/management/logs/online-store'
    | '/pos/management/logs/support'
    | '/pos/management/marketplace/settings'
    | '/pos/management/outlet/ho'
    | '/pos/management/outlet/kitchen'
    | '/pos/management/users/admin-groups'
    | '/pos/management/users/admin-management'
    | '/pos/management/users/biller-app'
    | '/pos/management/users/biller-groups'
    | '/pos/management/marketplace/'
    | '/pos/management/accounting/payments/information'
    | '/pos/management/accounting/payments/wallet'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pos'
    | '/pos/aggregators'
    | '/pos/billing'
    | '/pos/crm'
    | '/pos/help'
    | '/pos/inventory'
    | '/pos/kot'
    | '/pos/management'
    | '/pos/marketing'
    | '/pos/menu'
    | '/pos/orders'
    | '/pos/reports'
    | '/pos/room-service'
    | '/pos/settings'
    | '/pos/settlement'
    | '/pos/tables'
    | '/pos/inventory/available-stock'
    | '/pos/inventory/closing-stock'
    | '/pos/inventory/masters'
    | '/pos/inventory/order'
    | '/pos/inventory/production'
    | '/pos/inventory/purchase'
    | '/pos/inventory/reports'
    | '/pos/inventory/return'
    | '/pos/inventory/sales'
    | '/pos/inventory/sales-return'
    | '/pos/inventory/settings'
    | '/pos/inventory/transfer'
    | '/pos/inventory/wastage'
    | '/pos/management/audit-trail'
    | '/pos/management/data-management'
    | '/pos/management/device-mapping'
    | '/pos/menu/commission'
    | '/pos/menu/images'
    | '/pos/menu/on-off'
    | '/pos/menu/physical'
    | '/pos/menu/schedule'
    | '/pos/menu/special-notes'
    | '/pos/orders/all'
    | '/pos/orders/online'
    | '/pos/reports/day-end'
    | '/pos/reports/delivery'
    | '/pos/reports/notifications'
    | '/pos/reports/other'
    | '/pos/inventory/masters/invoice-templates'
    | '/pos/inventory/masters/purchase-payments'
    | '/pos/inventory/masters/raw-materials'
    | '/pos/inventory/masters/recipes'
    | '/pos/inventory/masters/suppliers'
    | '/pos/inventory/masters/units'
    | '/pos/inventory/production/barcode'
    | '/pos/inventory/production/execution'
    | '/pos/inventory/reports/orderwise-consumption'
    | '/pos/inventory/reports/other-reports'
    | '/pos/inventory/reports/stock-summary'
    | '/pos/management/accounting/bank-details'
    | '/pos/management/accounting/denomination'
    | '/pos/management/accounting/expenses'
    | '/pos/management/accounting/gst'
    | '/pos/management/accounting/kyc'
    | '/pos/management/accounting/loans'
    | '/pos/management/accounting/online-reconciliation'
    | '/pos/management/accounting/service-payments'
    | '/pos/management/accounting/utility-bills'
    | '/pos/management/configuration/area-delivery-charges'
    | '/pos/management/configuration/delivery-distance'
    | '/pos/management/configuration/email-templates'
    | '/pos/management/configuration/floor-plan'
    | '/pos/management/configuration/outlet'
    | '/pos/management/configuration/sub-order-type'
    | '/pos/management/logs/online-store'
    | '/pos/management/logs/support'
    | '/pos/management/marketplace/settings'
    | '/pos/management/outlet/ho'
    | '/pos/management/outlet/kitchen'
    | '/pos/management/users/admin-groups'
    | '/pos/management/users/admin-management'
    | '/pos/management/users/biller-app'
    | '/pos/management/users/biller-groups'
    | '/pos/management/marketplace'
    | '/pos/management/accounting/payments/information'
    | '/pos/management/accounting/payments/wallet'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/pos'
    | '/pos/aggregators'
    | '/pos/billing'
    | '/pos/crm'
    | '/pos/help'
    | '/pos/inventory'
    | '/pos/kot'
    | '/pos/management'
    | '/pos/marketing'
    | '/pos/menu'
    | '/pos/orders'
    | '/pos/reports'
    | '/pos/room-service'
    | '/pos/settings'
    | '/pos/settlement'
    | '/pos/tables'
    | '/pos/inventory/available-stock'
    | '/pos/inventory/closing-stock'
    | '/pos/inventory/masters'
    | '/pos/inventory/order'
    | '/pos/inventory/production'
    | '/pos/inventory/purchase'
    | '/pos/inventory/reports'
    | '/pos/inventory/return'
    | '/pos/inventory/sales'
    | '/pos/inventory/sales-return'
    | '/pos/inventory/settings'
    | '/pos/inventory/transfer'
    | '/pos/inventory/wastage'
    | '/pos/management/audit-trail'
    | '/pos/management/data-management'
    | '/pos/management/device-mapping'
    | '/pos/menu/commission'
    | '/pos/menu/images'
    | '/pos/menu/on-off'
    | '/pos/menu/physical'
    | '/pos/menu/schedule'
    | '/pos/menu/special-notes'
    | '/pos/orders/all'
    | '/pos/orders/online'
    | '/pos/reports/day-end'
    | '/pos/reports/delivery'
    | '/pos/reports/notifications'
    | '/pos/reports/other'
    | '/pos/inventory/masters/invoice-templates'
    | '/pos/inventory/masters/purchase-payments'
    | '/pos/inventory/masters/raw-materials'
    | '/pos/inventory/masters/recipes'
    | '/pos/inventory/masters/suppliers'
    | '/pos/inventory/masters/units'
    | '/pos/inventory/production/barcode'
    | '/pos/inventory/production/execution'
    | '/pos/inventory/reports/orderwise-consumption'
    | '/pos/inventory/reports/other-reports'
    | '/pos/inventory/reports/stock-summary'
    | '/pos/management/accounting/bank-details'
    | '/pos/management/accounting/denomination'
    | '/pos/management/accounting/expenses'
    | '/pos/management/accounting/gst'
    | '/pos/management/accounting/kyc'
    | '/pos/management/accounting/loans'
    | '/pos/management/accounting/online-reconciliation'
    | '/pos/management/accounting/service-payments'
    | '/pos/management/accounting/utility-bills'
    | '/pos/management/configuration/area-delivery-charges'
    | '/pos/management/configuration/delivery-distance'
    | '/pos/management/configuration/email-templates'
    | '/pos/management/configuration/floor-plan'
    | '/pos/management/configuration/outlet'
    | '/pos/management/configuration/sub-order-type'
    | '/pos/management/logs/online-store'
    | '/pos/management/logs/support'
    | '/pos/management/marketplace/settings'
    | '/pos/management/outlet/ho'
    | '/pos/management/outlet/kitchen'
    | '/pos/management/users/admin-groups'
    | '/pos/management/users/admin-management'
    | '/pos/management/users/biller-app'
    | '/pos/management/users/biller-groups'
    | '/pos/management/marketplace/'
    | '/pos/management/accounting/payments/information'
    | '/pos/management/accounting/payments/wallet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PosRoute: typeof PosRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos/tables': {
      id: '/pos/tables'
      path: '/tables'
      fullPath: '/pos/tables'
      preLoaderRoute: typeof PosTablesRouteImport
      parentRoute: typeof PosRoute
    }
    '/pos/settlement': {
      id: '/pos/settlement'
      path: '/settlement'
      fullPath: '/pos/settlement'
      preLoaderRoute: typeof PosSettlementRouteImport
      parentRoute: typeof PosRoute
    }
    '/pos/settings': {
      id: '/pos/settings'
      path: '/settings'
      fullPath: '/pos/settings'
      preLoaderRoute: typeof PosSettingsRouteImport
      parentRoute: typeof PosRoute
    }
    '/pos/room-service': {
      id: '/pos/room-service'
      path: '/room-service'
      fullPath: '/pos/room-service'
      preLoaderRoute: typeof PosRoomServiceRouteImport
      parentRoute: typeof PosRoute
    }
    '/pos/reports': {
      id: '/pos/reports'
      path: '/reports'
      fullPath: '/pos/reports'
      preLoaderRoute: typeof PosReportsRouteImport
      parentRoute: typeof PosRoute
    }
    '/pos/orders': {
      id: '/pos/orders'
      path: '/orders'
      fullPath: '/pos/orders'
      preLoaderRoute: typeof PosOrdersRouteImport
      parentRoute: typeof PosRoute
    }
    '/pos/menu': {
      id: '/pos/menu'
      path: '/menu'
      fullPath: '/pos/menu'
      preLoaderRoute: typeof PosMenuRouteImport
      parentRoute: typeof PosRoute
    }
    '/pos/marketing': {
      id: '/pos/marketing'
      path: '/marketing'
      fullPath: '/pos/marketing'
      preLoaderRoute: typeof PosMarketingRouteImport
      parentRoute: typeof PosRoute
    }
    '/pos/management': {
      id: '/pos/management'
      path: '/management'
      fullPath: '/pos/management'
      preLoaderRoute: typeof PosManagementRouteImport
      parentRoute: typeof PosRoute
    }
    '/pos/kot': {
      id: '/pos/kot'
      path: '/kot'
      fullPath: '/pos/kot'
      preLoaderRoute: typeof PosKotRouteImport
      parentRoute: typeof PosRoute
    }
    '/pos/inventory': {
      id: '/pos/inventory'
      path: '/inventory'
      fullPath: '/pos/inventory'
      preLoaderRoute: typeof PosInventoryRouteImport
      parentRoute: typeof PosRoute
    }
    '/pos/help': {
      id: '/pos/help'
      path: '/help'
      fullPath: '/pos/help'
      preLoaderRoute: typeof PosHelpRouteImport
      parentRoute: typeof PosRoute
    }
    '/pos/crm': {
      id: '/pos/crm'
      path: '/crm'
      fullPath: '/pos/crm'
      preLoaderRoute: typeof PosCrmRouteImport
      parentRoute: typeof PosRoute
    }
    '/pos/billing': {
      id: '/pos/billing'
      path: '/billing'
      fullPath: '/pos/billing'
      preLoaderRoute: typeof PosBillingRouteImport
      parentRoute: typeof PosRoute
    }
    '/pos/aggregators': {
      id: '/pos/aggregators'
      path: '/aggregators'
      fullPath: '/pos/aggregators'
      preLoaderRoute: typeof PosAggregatorsRouteImport
      parentRoute: typeof PosRoute
    }
    '/pos/reports/other': {
      id: '/pos/reports/other'
      path: '/other'
      fullPath: '/pos/reports/other'
      preLoaderRoute: typeof PosReportsOtherRouteImport
      parentRoute: typeof PosReportsRoute
    }
    '/pos/reports/notifications': {
      id: '/pos/reports/notifications'
      path: '/notifications'
      fullPath: '/pos/reports/notifications'
      preLoaderRoute: typeof PosReportsNotificationsRouteImport
      parentRoute: typeof PosReportsRoute
    }
    '/pos/reports/delivery': {
      id: '/pos/reports/delivery'
      path: '/delivery'
      fullPath: '/pos/reports/delivery'
      preLoaderRoute: typeof PosReportsDeliveryRouteImport
      parentRoute: typeof PosReportsRoute
    }
    '/pos/reports/day-end': {
      id: '/pos/reports/day-end'
      path: '/day-end'
      fullPath: '/pos/reports/day-end'
      preLoaderRoute: typeof PosReportsDayEndRouteImport
      parentRoute: typeof PosReportsRoute
    }
    '/pos/orders/online': {
      id: '/pos/orders/online'
      path: '/online'
      fullPath: '/pos/orders/online'
      preLoaderRoute: typeof PosOrdersOnlineRouteImport
      parentRoute: typeof PosOrdersRoute
    }
    '/pos/orders/all': {
      id: '/pos/orders/all'
      path: '/all'
      fullPath: '/pos/orders/all'
      preLoaderRoute: typeof PosOrdersAllRouteImport
      parentRoute: typeof PosOrdersRoute
    }
    '/pos/menu/special-notes': {
      id: '/pos/menu/special-notes'
      path: '/special-notes'
      fullPath: '/pos/menu/special-notes'
      preLoaderRoute: typeof PosMenuSpecialNotesRouteImport
      parentRoute: typeof PosMenuRoute
    }
    '/pos/menu/schedule': {
      id: '/pos/menu/schedule'
      path: '/schedule'
      fullPath: '/pos/menu/schedule'
      preLoaderRoute: typeof PosMenuScheduleRouteImport
      parentRoute: typeof PosMenuRoute
    }
    '/pos/menu/physical': {
      id: '/pos/menu/physical'
      path: '/physical'
      fullPath: '/pos/menu/physical'
      preLoaderRoute: typeof PosMenuPhysicalRouteImport
      parentRoute: typeof PosMenuRoute
    }
    '/pos/menu/on-off': {
      id: '/pos/menu/on-off'
      path: '/on-off'
      fullPath: '/pos/menu/on-off'
      preLoaderRoute: typeof PosMenuOnOffRouteImport
      parentRoute: typeof PosMenuRoute
    }
    '/pos/menu/images': {
      id: '/pos/menu/images'
      path: '/images'
      fullPath: '/pos/menu/images'
      preLoaderRoute: typeof PosMenuImagesRouteImport
      parentRoute: typeof PosMenuRoute
    }
    '/pos/menu/commission': {
      id: '/pos/menu/commission'
      path: '/commission'
      fullPath: '/pos/menu/commission'
      preLoaderRoute: typeof PosMenuCommissionRouteImport
      parentRoute: typeof PosMenuRoute
    }
    '/pos/management/device-mapping': {
      id: '/pos/management/device-mapping'
      path: '/device-mapping'
      fullPath: '/pos/management/device-mapping'
      preLoaderRoute: typeof PosManagementDeviceMappingRouteImport
      parentRoute: typeof PosManagementRoute
    }
    '/pos/management/data-management': {
      id: '/pos/management/data-management'
      path: '/data-management'
      fullPath: '/pos/management/data-management'
      preLoaderRoute: typeof PosManagementDataManagementRouteImport
      parentRoute: typeof PosManagementRoute
    }
    '/pos/management/audit-trail': {
      id: '/pos/management/audit-trail'
      path: '/audit-trail'
      fullPath: '/pos/management/audit-trail'
      preLoaderRoute: typeof PosManagementAuditTrailRouteImport
      parentRoute: typeof PosManagementRoute
    }
    '/pos/inventory/wastage': {
      id: '/pos/inventory/wastage'
      path: '/wastage'
      fullPath: '/pos/inventory/wastage'
      preLoaderRoute: typeof PosInventoryWastageRouteImport
      parentRoute: typeof PosInventoryRoute
    }
    '/pos/inventory/transfer': {
      id: '/pos/inventory/transfer'
      path: '/transfer'
      fullPath: '/pos/inventory/transfer'
      preLoaderRoute: typeof PosInventoryTransferRouteImport
      parentRoute: typeof PosInventoryRoute
    }
    '/pos/inventory/settings': {
      id: '/pos/inventory/settings'
      path: '/settings'
      fullPath: '/pos/inventory/settings'
      preLoaderRoute: typeof PosInventorySettingsRouteImport
      parentRoute: typeof PosInventoryRoute
    }
    '/pos/inventory/sales-return': {
      id: '/pos/inventory/sales-return'
      path: '/sales-return'
      fullPath: '/pos/inventory/sales-return'
      preLoaderRoute: typeof PosInventorySalesReturnRouteImport
      parentRoute: typeof PosInventoryRoute
    }
    '/pos/inventory/sales': {
      id: '/pos/inventory/sales'
      path: '/sales'
      fullPath: '/pos/inventory/sales'
      preLoaderRoute: typeof PosInventorySalesRouteImport
      parentRoute: typeof PosInventoryRoute
    }
    '/pos/inventory/return': {
      id: '/pos/inventory/return'
      path: '/return'
      fullPath: '/pos/inventory/return'
      preLoaderRoute: typeof PosInventoryReturnRouteImport
      parentRoute: typeof PosInventoryRoute
    }
    '/pos/inventory/reports': {
      id: '/pos/inventory/reports'
      path: '/reports'
      fullPath: '/pos/inventory/reports'
      preLoaderRoute: typeof PosInventoryReportsRouteImport
      parentRoute: typeof PosInventoryRoute
    }
    '/pos/inventory/purchase': {
      id: '/pos/inventory/purchase'
      path: '/purchase'
      fullPath: '/pos/inventory/purchase'
      preLoaderRoute: typeof PosInventoryPurchaseRouteImport
      parentRoute: typeof PosInventoryRoute
    }
    '/pos/inventory/production': {
      id: '/pos/inventory/production'
      path: '/production'
      fullPath: '/pos/inventory/production'
      preLoaderRoute: typeof PosInventoryProductionRouteImport
      parentRoute: typeof PosInventoryRoute
    }
    '/pos/inventory/order': {
      id: '/pos/inventory/order'
      path: '/order'
      fullPath: '/pos/inventory/order'
      preLoaderRoute: typeof PosInventoryOrderRouteImport
      parentRoute: typeof PosInventoryRoute
    }
    '/pos/inventory/masters': {
      id: '/pos/inventory/masters'
      path: '/masters'
      fullPath: '/pos/inventory/masters'
      preLoaderRoute: typeof PosInventoryMastersRouteImport
      parentRoute: typeof PosInventoryRoute
    }
    '/pos/inventory/closing-stock': {
      id: '/pos/inventory/closing-stock'
      path: '/closing-stock'
      fullPath: '/pos/inventory/closing-stock'
      preLoaderRoute: typeof PosInventoryClosingStockRouteImport
      parentRoute: typeof PosInventoryRoute
    }
    '/pos/inventory/available-stock': {
      id: '/pos/inventory/available-stock'
      path: '/available-stock'
      fullPath: '/pos/inventory/available-stock'
      preLoaderRoute: typeof PosInventoryAvailableStockRouteImport
      parentRoute: typeof PosInventoryRoute
    }
    '/pos/management/marketplace/': {
      id: '/pos/management/marketplace/'
      path: '/marketplace'
      fullPath: '/pos/management/marketplace/'
      preLoaderRoute: typeof PosManagementMarketplaceIndexRouteImport
      parentRoute: typeof PosManagementRoute
    }
    '/pos/management/users/biller-groups': {
      id: '/pos/management/users/biller-groups'
      path: '/users/biller-groups'
      fullPath: '/pos/management/users/biller-groups'
      preLoaderRoute: typeof PosManagementUsersBillerGroupsRouteImport
      parentRoute: typeof PosManagementRoute
    }
    '/pos/management/users/biller-app': {
      id: '/pos/management/users/biller-app'
      path: '/users/biller-app'
      fullPath: '/pos/management/users/biller-app'
      preLoaderRoute: typeof PosManagementUsersBillerAppRouteImport
      parentRoute: typeof PosManagementRoute
    }
    '/pos/management/users/admin-management': {
      id: '/pos/management/users/admin-management'
      path: '/users/admin-management'
      fullPath: '/pos/management/users/admin-management'
      preLoaderRoute: typeof PosManagementUsersAdminManagementRouteImport
      parentRoute: typeof PosManagementRoute
    }
    '/pos/management/users/admin-groups': {
      id: '/pos/management/users/admin-groups'
      path: '/users/admin-groups'
      fullPath: '/pos/management/users/admin-groups'
      preLoaderRoute: typeof PosManagementUsersAdminGroupsRouteImport
      parentRoute: typeof PosManagementRoute
    }
    '/pos/management/outlet/kitchen': {
      id: '/pos/management/outlet/kitchen'
      path: '/outlet/kitchen'
      fullPath: '/pos/management/outlet/kitchen'
      preLoaderRoute: typeof PosManagementOutletKitchenRouteImport
      parentRoute: typeof PosManagementRoute
    }
    '/pos/management/outlet/ho': {
      id: '/pos/management/outlet/ho'
      path: '/outlet/ho'
      fullPath: '/pos/management/outlet/ho'
      preLoaderRoute: typeof PosManagementOutletHoRouteImport
      parentRoute: typeof PosManagementRoute
    }
    '/pos/management/marketplace/settings': {
      id: '/pos/management/marketplace/settings'
      path: '/marketplace/settings'
      fullPath: '/pos/management/marketplace/settings'
      preLoaderRoute: typeof PosManagementMarketplaceSettingsRouteImport
      parentRoute: typeof PosManagementRoute
    }
    '/pos/management/logs/support': {
      id: '/pos/management/logs/support'
      path: '/logs/support'
      fullPath: '/pos/management/logs/support'
      preLoaderRoute: typeof PosManagementLogsSupportRouteImport
      parentRoute: typeof PosManagementRoute
    }
    '/pos/management/logs/online-store': {
      id: '/pos/management/logs/online-store'
      path: '/logs/online-store'
      fullPath: '/pos/management/logs/online-store'
      preLoaderRoute: typeof PosManagementLogsOnlineStoreRouteImport
      parentRoute: typeof PosManagementRoute
    }
    '/pos/management/configuration/sub-order-type': {
      id: '/pos/management/configuration/sub-order-type'
      path: '/configuration/sub-order-type'
      fullPath: '/pos/management/configuration/sub-order-type'
      preLoaderRoute: typeof PosManagementConfigurationSubOrderTypeRouteImport
      parentRoute: typeof PosManagementRoute
    }
    '/pos/management/configuration/outlet': {
      id: '/pos/management/configuration/outlet'
      path: '/configuration/outlet'
      fullPath: '/pos/management/configuration/outlet'
      preLoaderRoute: typeof PosManagementConfigurationOutletRouteImport
      parentRoute: typeof PosManagementRoute
    }
    '/pos/management/configuration/floor-plan': {
      id: '/pos/management/configuration/floor-plan'
      path: '/configuration/floor-plan'
      fullPath: '/pos/management/configuration/floor-plan'
      preLoaderRoute: typeof PosManagementConfigurationFloorPlanRouteImport
      parentRoute: typeof PosManagementRoute
    }
    '/pos/management/configuration/email-templates': {
      id: '/pos/management/configuration/email-templates'
      path: '/configuration/email-templates'
      fullPath: '/pos/management/configuration/email-templates'
      preLoaderRoute: typeof PosManagementConfigurationEmailTemplatesRouteImport
      parentRoute: typeof PosManagementRoute
    }
    '/pos/management/configuration/delivery-distance': {
      id: '/pos/management/configuration/delivery-distance'
      path: '/configuration/delivery-distance'
      fullPath: '/pos/management/configuration/delivery-distance'
      preLoaderRoute: typeof PosManagementConfigurationDeliveryDistanceRouteImport
      parentRoute: typeof PosManagementRoute
    }
    '/pos/management/configuration/area-delivery-charges': {
      id: '/pos/management/configuration/area-delivery-charges'
      path: '/configuration/area-delivery-charges'
      fullPath: '/pos/management/configuration/area-delivery-charges'
      preLoaderRoute: typeof PosManagementConfigurationAreaDeliveryChargesRouteImport
      parentRoute: typeof PosManagementRoute
    }
    '/pos/management/accounting/utility-bills': {
      id: '/pos/management/accounting/utility-bills'
      path: '/accounting/utility-bills'
      fullPath: '/pos/management/accounting/utility-bills'
      preLoaderRoute: typeof PosManagementAccountingUtilityBillsRouteImport
      parentRoute: typeof PosManagementRoute
    }
    '/pos/management/accounting/service-payments': {
      id: '/pos/management/accounting/service-payments'
      path: '/accounting/service-payments'
      fullPath: '/pos/management/accounting/service-payments'
      preLoaderRoute: typeof PosManagementAccountingServicePaymentsRouteImport
      parentRoute: typeof PosManagementRoute
    }
    '/pos/management/accounting/online-reconciliation': {
      id: '/pos/management/accounting/online-reconciliation'
      path: '/accounting/online-reconciliation'
      fullPath: '/pos/management/accounting/online-reconciliation'
      preLoaderRoute: typeof PosManagementAccountingOnlineReconciliationRouteImport
      parentRoute: typeof PosManagementRoute
    }
    '/pos/management/accounting/loans': {
      id: '/pos/management/accounting/loans'
      path: '/accounting/loans'
      fullPath: '/pos/management/accounting/loans'
      preLoaderRoute: typeof PosManagementAccountingLoansRouteImport
      parentRoute: typeof PosManagementRoute
    }
    '/pos/management/accounting/kyc': {
      id: '/pos/management/accounting/kyc'
      path: '/accounting/kyc'
      fullPath: '/pos/management/accounting/kyc'
      preLoaderRoute: typeof PosManagementAccountingKycRouteImport
      parentRoute: typeof PosManagementRoute
    }
    '/pos/management/accounting/gst': {
      id: '/pos/management/accounting/gst'
      path: '/accounting/gst'
      fullPath: '/pos/management/accounting/gst'
      preLoaderRoute: typeof PosManagementAccountingGstRouteImport
      parentRoute: typeof PosManagementRoute
    }
    '/pos/management/accounting/expenses': {
      id: '/pos/management/accounting/expenses'
      path: '/accounting/expenses'
      fullPath: '/pos/management/accounting/expenses'
      preLoaderRoute: typeof PosManagementAccountingExpensesRouteImport
      parentRoute: typeof PosManagementRoute
    }
    '/pos/management/accounting/denomination': {
      id: '/pos/management/accounting/denomination'
      path: '/accounting/denomination'
      fullPath: '/pos/management/accounting/denomination'
      preLoaderRoute: typeof PosManagementAccountingDenominationRouteImport
      parentRoute: typeof PosManagementRoute
    }
    '/pos/management/accounting/bank-details': {
      id: '/pos/management/accounting/bank-details'
      path: '/accounting/bank-details'
      fullPath: '/pos/management/accounting/bank-details'
      preLoaderRoute: typeof PosManagementAccountingBankDetailsRouteImport
      parentRoute: typeof PosManagementRoute
    }
    '/pos/inventory/reports/stock-summary': {
      id: '/pos/inventory/reports/stock-summary'
      path: '/stock-summary'
      fullPath: '/pos/inventory/reports/stock-summary'
      preLoaderRoute: typeof PosInventoryReportsStockSummaryRouteImport
      parentRoute: typeof PosInventoryReportsRoute
    }
    '/pos/inventory/reports/other-reports': {
      id: '/pos/inventory/reports/other-reports'
      path: '/other-reports'
      fullPath: '/pos/inventory/reports/other-reports'
      preLoaderRoute: typeof PosInventoryReportsOtherReportsRouteImport
      parentRoute: typeof PosInventoryReportsRoute
    }
    '/pos/inventory/reports/orderwise-consumption': {
      id: '/pos/inventory/reports/orderwise-consumption'
      path: '/orderwise-consumption'
      fullPath: '/pos/inventory/reports/orderwise-consumption'
      preLoaderRoute: typeof PosInventoryReportsOrderwiseConsumptionRouteImport
      parentRoute: typeof PosInventoryReportsRoute
    }
    '/pos/inventory/production/execution': {
      id: '/pos/inventory/production/execution'
      path: '/execution'
      fullPath: '/pos/inventory/production/execution'
      preLoaderRoute: typeof PosInventoryProductionExecutionRouteImport
      parentRoute: typeof PosInventoryProductionRoute
    }
    '/pos/inventory/production/barcode': {
      id: '/pos/inventory/production/barcode'
      path: '/barcode'
      fullPath: '/pos/inventory/production/barcode'
      preLoaderRoute: typeof PosInventoryProductionBarcodeRouteImport
      parentRoute: typeof PosInventoryProductionRoute
    }
    '/pos/inventory/masters/units': {
      id: '/pos/inventory/masters/units'
      path: '/units'
      fullPath: '/pos/inventory/masters/units'
      preLoaderRoute: typeof PosInventoryMastersUnitsRouteImport
      parentRoute: typeof PosInventoryMastersRoute
    }
    '/pos/inventory/masters/suppliers': {
      id: '/pos/inventory/masters/suppliers'
      path: '/suppliers'
      fullPath: '/pos/inventory/masters/suppliers'
      preLoaderRoute: typeof PosInventoryMastersSuppliersRouteImport
      parentRoute: typeof PosInventoryMastersRoute
    }
    '/pos/inventory/masters/recipes': {
      id: '/pos/inventory/masters/recipes'
      path: '/recipes'
      fullPath: '/pos/inventory/masters/recipes'
      preLoaderRoute: typeof PosInventoryMastersRecipesRouteImport
      parentRoute: typeof PosInventoryMastersRoute
    }
    '/pos/inventory/masters/raw-materials': {
      id: '/pos/inventory/masters/raw-materials'
      path: '/raw-materials'
      fullPath: '/pos/inventory/masters/raw-materials'
      preLoaderRoute: typeof PosInventoryMastersRawMaterialsRouteImport
      parentRoute: typeof PosInventoryMastersRoute
    }
    '/pos/inventory/masters/purchase-payments': {
      id: '/pos/inventory/masters/purchase-payments'
      path: '/purchase-payments'
      fullPath: '/pos/inventory/masters/purchase-payments'
      preLoaderRoute: typeof PosInventoryMastersPurchasePaymentsRouteImport
      parentRoute: typeof PosInventoryMastersRoute
    }
    '/pos/inventory/masters/invoice-templates': {
      id: '/pos/inventory/masters/invoice-templates'
      path: '/invoice-templates'
      fullPath: '/pos/inventory/masters/invoice-templates'
      preLoaderRoute: typeof PosInventoryMastersInvoiceTemplatesRouteImport
      parentRoute: typeof PosInventoryMastersRoute
    }
    '/pos/management/accounting/payments/wallet': {
      id: '/pos/management/accounting/payments/wallet'
      path: '/accounting/payments/wallet'
      fullPath: '/pos/management/accounting/payments/wallet'
      preLoaderRoute: typeof PosManagementAccountingPaymentsWalletRouteImport
      parentRoute: typeof PosManagementRoute
    }
    '/pos/management/accounting/payments/information': {
      id: '/pos/management/accounting/payments/information'
      path: '/accounting/payments/information'
      fullPath: '/pos/management/accounting/payments/information'
      preLoaderRoute: typeof PosManagementAccountingPaymentsInformationRouteImport
      parentRoute: typeof PosManagementRoute
    }
  }
}

interface PosInventoryMastersRouteChildren {
  PosInventoryMastersInvoiceTemplatesRoute: typeof PosInventoryMastersInvoiceTemplatesRoute
  PosInventoryMastersPurchasePaymentsRoute: typeof PosInventoryMastersPurchasePaymentsRoute
  PosInventoryMastersRawMaterialsRoute: typeof PosInventoryMastersRawMaterialsRoute
  PosInventoryMastersRecipesRoute: typeof PosInventoryMastersRecipesRoute
  PosInventoryMastersSuppliersRoute: typeof PosInventoryMastersSuppliersRoute
  PosInventoryMastersUnitsRoute: typeof PosInventoryMastersUnitsRoute
}

const PosInventoryMastersRouteChildren: PosInventoryMastersRouteChildren = {
  PosInventoryMastersInvoiceTemplatesRoute:
    PosInventoryMastersInvoiceTemplatesRoute,
  PosInventoryMastersPurchasePaymentsRoute:
    PosInventoryMastersPurchasePaymentsRoute,
  PosInventoryMastersRawMaterialsRoute: PosInventoryMastersRawMaterialsRoute,
  PosInventoryMastersRecipesRoute: PosInventoryMastersRecipesRoute,
  PosInventoryMastersSuppliersRoute: PosInventoryMastersSuppliersRoute,
  PosInventoryMastersUnitsRoute: PosInventoryMastersUnitsRoute,
}

const PosInventoryMastersRouteWithChildren =
  PosInventoryMastersRoute._addFileChildren(PosInventoryMastersRouteChildren)

interface PosInventoryProductionRouteChildren {
  PosInventoryProductionBarcodeRoute: typeof PosInventoryProductionBarcodeRoute
  PosInventoryProductionExecutionRoute: typeof PosInventoryProductionExecutionRoute
}

const PosInventoryProductionRouteChildren: PosInventoryProductionRouteChildren =
  {
    PosInventoryProductionBarcodeRoute: PosInventoryProductionBarcodeRoute,
    PosInventoryProductionExecutionRoute: PosInventoryProductionExecutionRoute,
  }

const PosInventoryProductionRouteWithChildren =
  PosInventoryProductionRoute._addFileChildren(
    PosInventoryProductionRouteChildren,
  )

interface PosInventoryReportsRouteChildren {
  PosInventoryReportsOrderwiseConsumptionRoute: typeof PosInventoryReportsOrderwiseConsumptionRoute
  PosInventoryReportsOtherReportsRoute: typeof PosInventoryReportsOtherReportsRoute
  PosInventoryReportsStockSummaryRoute: typeof PosInventoryReportsStockSummaryRoute
}

const PosInventoryReportsRouteChildren: PosInventoryReportsRouteChildren = {
  PosInventoryReportsOrderwiseConsumptionRoute:
    PosInventoryReportsOrderwiseConsumptionRoute,
  PosInventoryReportsOtherReportsRoute: PosInventoryReportsOtherReportsRoute,
  PosInventoryReportsStockSummaryRoute: PosInventoryReportsStockSummaryRoute,
}

const PosInventoryReportsRouteWithChildren =
  PosInventoryReportsRoute._addFileChildren(PosInventoryReportsRouteChildren)

interface PosInventoryRouteChildren {
  PosInventoryAvailableStockRoute: typeof PosInventoryAvailableStockRoute
  PosInventoryClosingStockRoute: typeof PosInventoryClosingStockRoute
  PosInventoryMastersRoute: typeof PosInventoryMastersRouteWithChildren
  PosInventoryOrderRoute: typeof PosInventoryOrderRoute
  PosInventoryProductionRoute: typeof PosInventoryProductionRouteWithChildren
  PosInventoryPurchaseRoute: typeof PosInventoryPurchaseRoute
  PosInventoryReportsRoute: typeof PosInventoryReportsRouteWithChildren
  PosInventoryReturnRoute: typeof PosInventoryReturnRoute
  PosInventorySalesRoute: typeof PosInventorySalesRoute
  PosInventorySalesReturnRoute: typeof PosInventorySalesReturnRoute
  PosInventorySettingsRoute: typeof PosInventorySettingsRoute
  PosInventoryTransferRoute: typeof PosInventoryTransferRoute
  PosInventoryWastageRoute: typeof PosInventoryWastageRoute
}

const PosInventoryRouteChildren: PosInventoryRouteChildren = {
  PosInventoryAvailableStockRoute: PosInventoryAvailableStockRoute,
  PosInventoryClosingStockRoute: PosInventoryClosingStockRoute,
  PosInventoryMastersRoute: PosInventoryMastersRouteWithChildren,
  PosInventoryOrderRoute: PosInventoryOrderRoute,
  PosInventoryProductionRoute: PosInventoryProductionRouteWithChildren,
  PosInventoryPurchaseRoute: PosInventoryPurchaseRoute,
  PosInventoryReportsRoute: PosInventoryReportsRouteWithChildren,
  PosInventoryReturnRoute: PosInventoryReturnRoute,
  PosInventorySalesRoute: PosInventorySalesRoute,
  PosInventorySalesReturnRoute: PosInventorySalesReturnRoute,
  PosInventorySettingsRoute: PosInventorySettingsRoute,
  PosInventoryTransferRoute: PosInventoryTransferRoute,
  PosInventoryWastageRoute: PosInventoryWastageRoute,
}

const PosInventoryRouteWithChildren = PosInventoryRoute._addFileChildren(
  PosInventoryRouteChildren,
)

interface PosManagementRouteChildren {
  PosManagementAuditTrailRoute: typeof PosManagementAuditTrailRoute
  PosManagementDataManagementRoute: typeof PosManagementDataManagementRoute
  PosManagementDeviceMappingRoute: typeof PosManagementDeviceMappingRoute
  PosManagementAccountingBankDetailsRoute: typeof PosManagementAccountingBankDetailsRoute
  PosManagementAccountingDenominationRoute: typeof PosManagementAccountingDenominationRoute
  PosManagementAccountingExpensesRoute: typeof PosManagementAccountingExpensesRoute
  PosManagementAccountingGstRoute: typeof PosManagementAccountingGstRoute
  PosManagementAccountingKycRoute: typeof PosManagementAccountingKycRoute
  PosManagementAccountingLoansRoute: typeof PosManagementAccountingLoansRoute
  PosManagementAccountingOnlineReconciliationRoute: typeof PosManagementAccountingOnlineReconciliationRoute
  PosManagementAccountingServicePaymentsRoute: typeof PosManagementAccountingServicePaymentsRoute
  PosManagementAccountingUtilityBillsRoute: typeof PosManagementAccountingUtilityBillsRoute
  PosManagementConfigurationAreaDeliveryChargesRoute: typeof PosManagementConfigurationAreaDeliveryChargesRoute
  PosManagementConfigurationDeliveryDistanceRoute: typeof PosManagementConfigurationDeliveryDistanceRoute
  PosManagementConfigurationEmailTemplatesRoute: typeof PosManagementConfigurationEmailTemplatesRoute
  PosManagementConfigurationFloorPlanRoute: typeof PosManagementConfigurationFloorPlanRoute
  PosManagementConfigurationOutletRoute: typeof PosManagementConfigurationOutletRoute
  PosManagementConfigurationSubOrderTypeRoute: typeof PosManagementConfigurationSubOrderTypeRoute
  PosManagementLogsOnlineStoreRoute: typeof PosManagementLogsOnlineStoreRoute
  PosManagementLogsSupportRoute: typeof PosManagementLogsSupportRoute
  PosManagementMarketplaceSettingsRoute: typeof PosManagementMarketplaceSettingsRoute
  PosManagementOutletHoRoute: typeof PosManagementOutletHoRoute
  PosManagementOutletKitchenRoute: typeof PosManagementOutletKitchenRoute
  PosManagementUsersAdminGroupsRoute: typeof PosManagementUsersAdminGroupsRoute
  PosManagementUsersAdminManagementRoute: typeof PosManagementUsersAdminManagementRoute
  PosManagementUsersBillerAppRoute: typeof PosManagementUsersBillerAppRoute
  PosManagementUsersBillerGroupsRoute: typeof PosManagementUsersBillerGroupsRoute
  PosManagementMarketplaceIndexRoute: typeof PosManagementMarketplaceIndexRoute
  PosManagementAccountingPaymentsInformationRoute: typeof PosManagementAccountingPaymentsInformationRoute
  PosManagementAccountingPaymentsWalletRoute: typeof PosManagementAccountingPaymentsWalletRoute
}

const PosManagementRouteChildren: PosManagementRouteChildren = {
  PosManagementAuditTrailRoute: PosManagementAuditTrailRoute,
  PosManagementDataManagementRoute: PosManagementDataManagementRoute,
  PosManagementDeviceMappingRoute: PosManagementDeviceMappingRoute,
  PosManagementAccountingBankDetailsRoute:
    PosManagementAccountingBankDetailsRoute,
  PosManagementAccountingDenominationRoute:
    PosManagementAccountingDenominationRoute,
  PosManagementAccountingExpensesRoute: PosManagementAccountingExpensesRoute,
  PosManagementAccountingGstRoute: PosManagementAccountingGstRoute,
  PosManagementAccountingKycRoute: PosManagementAccountingKycRoute,
  PosManagementAccountingLoansRoute: PosManagementAccountingLoansRoute,
  PosManagementAccountingOnlineReconciliationRoute:
    PosManagementAccountingOnlineReconciliationRoute,
  PosManagementAccountingServicePaymentsRoute:
    PosManagementAccountingServicePaymentsRoute,
  PosManagementAccountingUtilityBillsRoute:
    PosManagementAccountingUtilityBillsRoute,
  PosManagementConfigurationAreaDeliveryChargesRoute:
    PosManagementConfigurationAreaDeliveryChargesRoute,
  PosManagementConfigurationDeliveryDistanceRoute:
    PosManagementConfigurationDeliveryDistanceRoute,
  PosManagementConfigurationEmailTemplatesRoute:
    PosManagementConfigurationEmailTemplatesRoute,
  PosManagementConfigurationFloorPlanRoute:
    PosManagementConfigurationFloorPlanRoute,
  PosManagementConfigurationOutletRoute: PosManagementConfigurationOutletRoute,
  PosManagementConfigurationSubOrderTypeRoute:
    PosManagementConfigurationSubOrderTypeRoute,
  PosManagementLogsOnlineStoreRoute: PosManagementLogsOnlineStoreRoute,
  PosManagementLogsSupportRoute: PosManagementLogsSupportRoute,
  PosManagementMarketplaceSettingsRoute: PosManagementMarketplaceSettingsRoute,
  PosManagementOutletHoRoute: PosManagementOutletHoRoute,
  PosManagementOutletKitchenRoute: PosManagementOutletKitchenRoute,
  PosManagementUsersAdminGroupsRoute: PosManagementUsersAdminGroupsRoute,
  PosManagementUsersAdminManagementRoute:
    PosManagementUsersAdminManagementRoute,
  PosManagementUsersBillerAppRoute: PosManagementUsersBillerAppRoute,
  PosManagementUsersBillerGroupsRoute: PosManagementUsersBillerGroupsRoute,
  PosManagementMarketplaceIndexRoute: PosManagementMarketplaceIndexRoute,
  PosManagementAccountingPaymentsInformationRoute:
    PosManagementAccountingPaymentsInformationRoute,
  PosManagementAccountingPaymentsWalletRoute:
    PosManagementAccountingPaymentsWalletRoute,
}

const PosManagementRouteWithChildren = PosManagementRoute._addFileChildren(
  PosManagementRouteChildren,
)

interface PosMenuRouteChildren {
  PosMenuCommissionRoute: typeof PosMenuCommissionRoute
  PosMenuImagesRoute: typeof PosMenuImagesRoute
  PosMenuOnOffRoute: typeof PosMenuOnOffRoute
  PosMenuPhysicalRoute: typeof PosMenuPhysicalRoute
  PosMenuScheduleRoute: typeof PosMenuScheduleRoute
  PosMenuSpecialNotesRoute: typeof PosMenuSpecialNotesRoute
}

const PosMenuRouteChildren: PosMenuRouteChildren = {
  PosMenuCommissionRoute: PosMenuCommissionRoute,
  PosMenuImagesRoute: PosMenuImagesRoute,
  PosMenuOnOffRoute: PosMenuOnOffRoute,
  PosMenuPhysicalRoute: PosMenuPhysicalRoute,
  PosMenuScheduleRoute: PosMenuScheduleRoute,
  PosMenuSpecialNotesRoute: PosMenuSpecialNotesRoute,
}

const PosMenuRouteWithChildren =
  PosMenuRoute._addFileChildren(PosMenuRouteChildren)

interface PosOrdersRouteChildren {
  PosOrdersAllRoute: typeof PosOrdersAllRoute
  PosOrdersOnlineRoute: typeof PosOrdersOnlineRoute
}

const PosOrdersRouteChildren: PosOrdersRouteChildren = {
  PosOrdersAllRoute: PosOrdersAllRoute,
  PosOrdersOnlineRoute: PosOrdersOnlineRoute,
}

const PosOrdersRouteWithChildren = PosOrdersRoute._addFileChildren(
  PosOrdersRouteChildren,
)

interface PosReportsRouteChildren {
  PosReportsDayEndRoute: typeof PosReportsDayEndRoute
  PosReportsDeliveryRoute: typeof PosReportsDeliveryRoute
  PosReportsNotificationsRoute: typeof PosReportsNotificationsRoute
  PosReportsOtherRoute: typeof PosReportsOtherRoute
}

const PosReportsRouteChildren: PosReportsRouteChildren = {
  PosReportsDayEndRoute: PosReportsDayEndRoute,
  PosReportsDeliveryRoute: PosReportsDeliveryRoute,
  PosReportsNotificationsRoute: PosReportsNotificationsRoute,
  PosReportsOtherRoute: PosReportsOtherRoute,
}

const PosReportsRouteWithChildren = PosReportsRoute._addFileChildren(
  PosReportsRouteChildren,
)

interface PosRouteChildren {
  PosAggregatorsRoute: typeof PosAggregatorsRoute
  PosBillingRoute: typeof PosBillingRoute
  PosCrmRoute: typeof PosCrmRoute
  PosHelpRoute: typeof PosHelpRoute
  PosInventoryRoute: typeof PosInventoryRouteWithChildren
  PosKotRoute: typeof PosKotRoute
  PosManagementRoute: typeof PosManagementRouteWithChildren
  PosMarketingRoute: typeof PosMarketingRoute
  PosMenuRoute: typeof PosMenuRouteWithChildren
  PosOrdersRoute: typeof PosOrdersRouteWithChildren
  PosReportsRoute: typeof PosReportsRouteWithChildren
  PosRoomServiceRoute: typeof PosRoomServiceRoute
  PosSettingsRoute: typeof PosSettingsRoute
  PosSettlementRoute: typeof PosSettlementRoute
  PosTablesRoute: typeof PosTablesRoute
}

const PosRouteChildren: PosRouteChildren = {
  PosAggregatorsRoute: PosAggregatorsRoute,
  PosBillingRoute: PosBillingRoute,
  PosCrmRoute: PosCrmRoute,
  PosHelpRoute: PosHelpRoute,
  PosInventoryRoute: PosInventoryRouteWithChildren,
  PosKotRoute: PosKotRoute,
  PosManagementRoute: PosManagementRouteWithChildren,
  PosMarketingRoute: PosMarketingRoute,
  PosMenuRoute: PosMenuRouteWithChildren,
  PosOrdersRoute: PosOrdersRouteWithChildren,
  PosReportsRoute: PosReportsRouteWithChildren,
  PosRoomServiceRoute: PosRoomServiceRoute,
  PosSettingsRoute: PosSettingsRoute,
  PosSettlementRoute: PosSettlementRoute,
  PosTablesRoute: PosTablesRoute,
}

const PosRouteWithChildren = PosRoute._addFileChildren(PosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PosRoute: PosRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
